#ifndef __STRING_ID_GLOBALS_H__
#define __STRING_ID_GLOBALS_H__
#pragma once

/* ---------- headers */

#include "tag_files/string_ids.h"

/* ---------- constants */

enum e_string_id_global
{
    k_string_id_empty_string = _string_id_empty_string,
    STRING_ID_ENTRY(global, default), // 1
    STRING_ID_ENTRY(global, reload_1), // 2
    STRING_ID_ENTRY(global, reload_2), // 3
    STRING_ID_ENTRY(global, chamber_1), // 4
    STRING_ID_ENTRY(global, chamber_2), // 5
    STRING_ID_ENTRY(global, fire_1), // 6
    STRING_ID_ENTRY(global, fire_2), // 7
    STRING_ID_ENTRY(global, charged_1), // 8
    STRING_ID_ENTRY(global, charged_2), // 9
    STRING_ID_ENTRY(global, melee), // 0xA
    STRING_ID_ENTRY(global, overheat), // 0xB
    STRING_ID_ENTRY(global, idle), // 0xC
    STRING_ID_ENTRY(global, gesture), // 0xD
    STRING_ID_ENTRY(global, turn_absolute), // 0xE
    STRING_ID_ENTRY(global, turn_left), // 0xF
    STRING_ID_ENTRY(global, turn_right), // 0x10
    STRING_ID_ENTRY(global, dive_front), // 0x11
    STRING_ID_ENTRY(global, dive_back), // 0x12
    STRING_ID_ENTRY(global, dive_left), // 0x13
    STRING_ID_ENTRY(global, dive_right), // 0x14
    STRING_ID_ENTRY(global, move_front), // 0x15
    STRING_ID_ENTRY(global, move_back), // 0x16
    STRING_ID_ENTRY(global, move_left), // 0x17
    STRING_ID_ENTRY(global, move_right), // 0x18
    STRING_ID_ENTRY(global, slide_front), // 0x19
    STRING_ID_ENTRY(global, slide_back), // 0x1A
    STRING_ID_ENTRY(global, slide_left), // 0x1B
    STRING_ID_ENTRY(global, slide_right), // 0x1C
    STRING_ID_ENTRY(global, climb_up), // 0x1D
    STRING_ID_ENTRY(global, climb_down), // 0x1E
    STRING_ID_ENTRY(global, airborne), // 0x1F
    STRING_ID_ENTRY(global, land_soft), // 0x20
    STRING_ID_ENTRY(global, land_hard), // 0x21
    STRING_ID_ENTRY(global, throw_grenade), // 0x22
    STRING_ID_ENTRY(global, disarm), // 0x23
    STRING_ID_ENTRY(global, drop), // 0x24
    STRING_ID_ENTRY(global, ready), // 0x25
    STRING_ID_ENTRY(global, put_away), // 0x26
    STRING_ID_ENTRY(global, weapon_stow_anchor), // 0x27
    STRING_ID_ENTRY(global, aim_still_up), // 0x28
    STRING_ID_ENTRY(global, aim_move_up), // 0x29
    STRING_ID_ENTRY(global, aim_still_down), // 0x2A
    STRING_ID_ENTRY(global, aim_move_down), // 0x2B
    STRING_ID_ENTRY(global, surprise_front), // 0x2C
    STRING_ID_ENTRY(global, surprise_back), // 0x2D
    STRING_ID_ENTRY(global, order_search), // 0x2E
    STRING_ID_ENTRY(global, order_attack), // 0x2F
    STRING_ID_ENTRY(global, order_grenade), // 0x30
    STRING_ID_ENTRY(global, found), // 0x31
    STRING_ID_ENTRY(global, berserk), // 0x32
    STRING_ID_ENTRY(global, go_berserk), // 0x33
    STRING_ID_ENTRY(global, go_kamikaze), // 0x34
    STRING_ID_ENTRY(global, evade_left), // 0x35
    STRING_ID_ENTRY(global, evade_right), // 0x36
    STRING_ID_ENTRY(global, evade_front), // 0x37
    STRING_ID_ENTRY(global, evade_back), // 0x38
    STRING_ID_ENTRY(global, signal_move), // 0x39
    STRING_ID_ENTRY(global, signal_attack), // 0x3A
    STRING_ID_ENTRY(global, warn), // 0x3B
    STRING_ID_ENTRY(global, sniff), // 0x3C
    STRING_ID_ENTRY(global, track), // 0x3D
    STRING_ID_ENTRY(global, stunned_front), // 0x3E
    STRING_ID_ENTRY(global, stunned_back), // 0x3F
    STRING_ID_ENTRY(global, stunned_left), // 0x40
    STRING_ID_ENTRY(global, stunned_right), // 0x41
    STRING_ID_ENTRY(global, celebrate), // 0x42
    STRING_ID_ENTRY(global, panic), // 0x43
    STRING_ID_ENTRY(global, melee_airborne), // 0x44
    STRING_ID_ENTRY(global, flaming), // 0x45
    STRING_ID_ENTRY(global, resurrect_front), // 0x46
    STRING_ID_ENTRY(global, resurrect_back), // 0x47
    STRING_ID_ENTRY(global, melee_continuous), // 0x48
    STRING_ID_ENTRY(global, feeding), // 0x49
    STRING_ID_ENTRY(global, leap_start), // 0x4A
    STRING_ID_ENTRY(global, leap_airborne), // 0x4B
    STRING_ID_ENTRY(global, leap_melee), // 0x4C
    STRING_ID_ENTRY(global, airborne_dead), // 0x4D
    STRING_ID_ENTRY(global, landing_dead), // 0x4E
    STRING_ID_ENTRY(global, acc_front_back), // 0x4F
    STRING_ID_ENTRY(global, acc_left_right), // 0x50
    STRING_ID_ENTRY(global, acc_up_down), // 0x51
    STRING_ID_ENTRY(global, enter), // 0x52
    STRING_ID_ENTRY(global, exit), // 0x53
    STRING_ID_ENTRY(global, exit_patrol), // 0x54
    STRING_ID_ENTRY(global, look), // 0x55
    STRING_ID_ENTRY(global, talk), // 0x56
    STRING_ID_ENTRY(global, l_lift_aim), // 0x57
    STRING_ID_ENTRY(global, r_lift_aim), // 0x58
    STRING_ID_ENTRY(global, flying_front), // 0x59
    STRING_ID_ENTRY(global, flying_back), // 0x5A
    STRING_ID_ENTRY(global, flying_left), // 0x5B
    STRING_ID_ENTRY(global, flying_right), // 0x5C
    STRING_ID_ENTRY(global, opening), // 0x5D
    STRING_ID_ENTRY(global, closing), // 0x5E
    STRING_ID_ENTRY(global, hovering), // 0x5F
    STRING_ID_ENTRY(global, posing), // 0x60
    STRING_ID_ENTRY(global, moving), // 0x61
    STRING_ID_ENTRY(global, overlays), // 0x62
    STRING_ID_ENTRY(global, light_off), // 0x63
    STRING_ID_ENTRY(global, light_on), // 0x64
    STRING_ID_ENTRY(global, reload_empty), // 0x65
    STRING_ID_ENTRY(global, reload_full), // 0x66
    STRING_ID_ENTRY(global, overheated), // 0x67
    STRING_ID_ENTRY(global, overcharged), // 0x68
    STRING_ID_ENTRY(global, overcharged_jitter), // 0x69
    STRING_ID_ENTRY(global, ammunition), // 0x6A
    STRING_ID_ENTRY(global, misfire_1), // 0x6B
    STRING_ID_ENTRY(global, misfire_2), // 0x6C
    STRING_ID_ENTRY(global, throw_overheated), // 0x6D
    STRING_ID_ENTRY(global, overheating), // 0x6E
    STRING_ID_ENTRY(global, ready_overheated), // 0x6F
    STRING_ID_ENTRY(global, exit_empty), // 0x70
    STRING_ID_ENTRY(global, exit_full), // 0x71
    STRING_ID_ENTRY(global, o_h_exit), // 0x72
    STRING_ID_ENTRY(global, o_h_s_enter), // 0x73
    STRING_ID_ENTRY(global, melee_1sthit), // 0x74
    STRING_ID_ENTRY(global, melee_1sthit2idle), // 0x75
    STRING_ID_ENTRY(global, melee_2ndhit), // 0x76
    STRING_ID_ENTRY(global, melee_2ndhit2idle), // 0x77
    STRING_ID_ENTRY(global, melee_3rdhit), // 0x78
    STRING_ID_ENTRY(global, steering), // 0x79
    STRING_ID_ENTRY(global, roll), // 0x7A
    STRING_ID_ENTRY(global, throttle), // 0x7B
    STRING_ID_ENTRY(global, velocity), // 0x7C
    STRING_ID_ENTRY(global, braking), // 0x7D
    STRING_ID_ENTRY(global, ground_speed), // 0x7E
    STRING_ID_ENTRY(global, occupied), // 0x7F
    STRING_ID_ENTRY(global, unoccupied), // 0x80
    STRING_ID_ENTRY(global, position), // 0x81
    STRING_ID_ENTRY(global, power), // 0x82
    STRING_ID_ENTRY(global, c_dropship), // 0x83
    STRING_ID_ENTRY(global, unarmed), // 0x84
    STRING_ID_ENTRY(global, asleep), // 0x85
    STRING_ID_ENTRY(global, patrol), // 0x86
    STRING_ID_ENTRY(global, combat), // 0x87
    STRING_ID_ENTRY(global, armored), // 0x88
    STRING_ID_ENTRY(global, protected), // 0x89
    STRING_ID_ENTRY(global, crouch), // 0x8A
    STRING_ID_ENTRY(global, active_camouflage), // 0x8B
    STRING_ID_ENTRY(global, bubbleshield), // 0x8C
    STRING_ID_ENTRY(global, flee), // 0x8D
    STRING_ID_ENTRY(global, unused), // 0x8E
    STRING_ID_ENTRY(global, s_ping), // 0x8F
    STRING_ID_ENTRY(global, h_ping), // 0x90
    STRING_ID_ENTRY(global, s_kill), // 0x91
    STRING_ID_ENTRY(global, h_kill), // 0x92
    STRING_ID_ENTRY(global, front), // 0x93
    STRING_ID_ENTRY(global, left), // 0x94
    STRING_ID_ENTRY(global, right), // 0x95
    STRING_ID_ENTRY(global, back), // 0x96
    STRING_ID_ENTRY(global, gut), // 0x97
    STRING_ID_ENTRY(global, chest), // 0x98
    STRING_ID_ENTRY(global, head), // 0x99
    STRING_ID_ENTRY(global, autoaim_melee), // 0x9A
    STRING_ID_ENTRY(global, l_arm), // 0x9B
    STRING_ID_ENTRY(global, l_hand), // 0x9C
    STRING_ID_ENTRY(global, l_leg), // 0x9D
    STRING_ID_ENTRY(global, l_foot), // 0x9E
    STRING_ID_ENTRY(global, r_arm), // 0x9F
    STRING_ID_ENTRY(global, r_hand), // 0xA0
    STRING_ID_ENTRY(global, r_leg), // 0xA1
    STRING_ID_ENTRY(global, r_foot), // 0xA2
    STRING_ID_ENTRY(global, center), // 0xA3
    STRING_ID_ENTRY(global, water_surface), // 0xA4
    STRING_ID_ENTRY(global, structure_surface), // 0xA5
    STRING_ID_ENTRY(global, flashlight), // 0xA6
    STRING_ID_ENTRY(global, flashlight_intensity), // 0xA7
    STRING_ID_ENTRY(global, incident), // 0xA8
    STRING_ID_ENTRY(global, normal), // 0xA9
    STRING_ID_ENTRY(global, midpoint), // 0xAA
    STRING_ID_ENTRY(global, hover_thrusters), // 0xAB
    STRING_ID_ENTRY(global, jet_thrusters), // 0xAC
    STRING_ID_ENTRY(global, body), // 0xAD
    STRING_ID_ENTRY(global, negative_incident), // 0xAE
    STRING_ID_ENTRY(global, reflection), // 0xAF
    STRING_ID_ENTRY(global, gravity), // 0xB0
    STRING_ID_ENTRY(global, user_animation), // 0xB1
    STRING_ID_ENTRY(global, ai_impulse), // 0xB2
    STRING_ID_ENTRY(global, board), // 0xB3
    STRING_ID_ENTRY(global, ejection), // 0xB4
    STRING_ID_ENTRY(global, stunned), // 0xB5
    STRING_ID_ENTRY(global, up), // 0xB6
    STRING_ID_ENTRY(global, climb), // 0xB7
    STRING_ID_ENTRY(global, attach), // 0xB8
    STRING_ID_ENTRY(global, detach), // 0xB9
    STRING_ID_ENTRY(global, weapon), // 0xBA
    STRING_ID_ENTRY(global, vehicle), // 0xBB
    STRING_ID_ENTRY(global, suspension), // 0xBC
    STRING_ID_ENTRY(global, device), // 0xBD
    STRING_ID_ENTRY(global, object), // 0xBE
    STRING_ID_ENTRY(global, masterchief), // 0xBF
    STRING_ID_ENTRY(global, dervish), // 0xC0
    STRING_ID_ENTRY(global, sprint), // 0xC1
    STRING_ID_ENTRY(global, any), // 0xC2
    STRING_ID_ENTRY(global, first_person), // 0xC3
    STRING_ID_ENTRY(global, primary_trigger), // 0xC4
    STRING_ID_ENTRY(global, secondary_trigger), // 0xC5
    STRING_ID_ENTRY(global, fp_body_cam), // 0xC6
    STRING_ID_ENTRY(global, pitch_and_turn), // 0xC7
    STRING_ID_ENTRY(global, tread), // 0xC8
    STRING_ID_ENTRY(global, camera_control), // 0xC9
    STRING_ID_ENTRY(global, mp_1st_place), // 0xCA
    STRING_ID_ENTRY(global, mp_2nd_place), // 0xCB
    STRING_ID_ENTRY(global, mp_3rd_place), // 0xCC
    STRING_ID_ENTRY(global, mp_4th_place), // 0xCD
    STRING_ID_ENTRY(global, mp_5th_place), // 0xCE
    STRING_ID_ENTRY(global, mp_6th_place), // 0xCF
    STRING_ID_ENTRY(global, mp_7th_place), // 0xD0
    STRING_ID_ENTRY(global, mp_8th_place), // 0xD1
    STRING_ID_ENTRY(global, mp_9th_place), // 0xD2
    STRING_ID_ENTRY(global, mp_10th_place), // 0xD3
    STRING_ID_ENTRY(global, mp_11th_place), // 0xD4
    STRING_ID_ENTRY(global, mp_12th_place), // 0xD5
    STRING_ID_ENTRY(global, mp_13th_place), // 0xD6
    STRING_ID_ENTRY(global, mp_14th_place), // 0xD7
    STRING_ID_ENTRY(global, mp_15th_place), // 0xD8
    STRING_ID_ENTRY(global, mp_16th_place), // 0xD9
    STRING_ID_ENTRY(global, mp_wins), // 0xDA
    STRING_ID_ENTRY(global, left_hand), // 0xDB
    STRING_ID_ENTRY(global, current), // 0xDC
    STRING_ID_ENTRY(global, mp_score), // 0xDD
    STRING_ID_ENTRY(global, mp_name), // 0xDE
    STRING_ID_ENTRY(global, mp_game_over), // 0xDF
    STRING_ID_ENTRY(global, mp_round_over), // 0xE0
    STRING_ID_ENTRY(global, mp_waiting_for_next_round), // 0xE1
    STRING_ID_ENTRY(global, capture_the_flag), // 0xE2
    STRING_ID_ENTRY(global, assault), // 0xE3
    STRING_ID_ENTRY(global, slayer), // 0xE4
    STRING_ID_ENTRY(global, oddball), // 0xE5
    STRING_ID_ENTRY(global, king_of_the_hill), // 0xE6
    STRING_ID_ENTRY(global, juggernaut), // 0xE7
    STRING_ID_ENTRY(global, vip), // 0xE8
    STRING_ID_ENTRY(global, territories), // 0xE9
    STRING_ID_ENTRY(global, infection), // 0xEA
    STRING_ID_ENTRY(global, sandbox), // 0xEB
    STRING_ID_ENTRY(global, dry), // 0xEC
    STRING_ID_ENTRY(global, sfx_extra_sound_inputs), // 0xED
    STRING_ID_ENTRY(global, controller_0_headset), // 0xEE
    STRING_ID_ENTRY(global, controller_1_headset), // 0xEF
    STRING_ID_ENTRY(global, controller_2_headset), // 0xF0
    STRING_ID_ENTRY(global, controller_3_headset), // 0xF1
    STRING_ID_ENTRY(global, unknown), // 0xF2
    STRING_ID_ENTRY(global, on), // 0xF3
    STRING_ID_ENTRY(global, off), // 0xF4
    STRING_ID_ENTRY(global, enabled), // 0xF5
    STRING_ID_ENTRY(global, disabled), // 0xF6
    STRING_ID_ENTRY(global, category), // 0xF7
    STRING_ID_ENTRY(global, mp_score_flags_header), // 0xF8
    STRING_ID_ENTRY(global, mp_score_laps_header), // 0xF9
    STRING_ID_ENTRY(global, eye_left), // 0xFA
    STRING_ID_ENTRY(global, eye_right), // 0xFB
    STRING_ID_ENTRY(global, ui), // 0xFC
    STRING_ID_ENTRY(global, corner_cover_left), // 0xFD
    STRING_ID_ENTRY(global, corner_cover_right), // 0xFE
    STRING_ID_ENTRY(global, leave_game), // 0xFF
    STRING_ID_ENTRY(global, change_teams), // 0x100
    STRING_ID_ENTRY(global, end_game), // 0x101
    STRING_ID_ENTRY(global, not_squad_leader), // 0x102
    STRING_ID_ENTRY(global, value), // 0x103
    STRING_ID_ENTRY(global, open), // 0x104
    STRING_ID_ENTRY(global, friends_only), // 0x105
    STRING_ID_ENTRY(global, invitation_only), // 0x106
    STRING_ID_ENTRY(global, closed), // 0x107
    STRING_ID_ENTRY(global, none), // 0x108
    STRING_ID_ENTRY(global, corner_open_left), // 0x109
    STRING_ID_ENTRY(global, corner_open_right), // 0x10A
    STRING_ID_ENTRY(global, impact), // 0x10B
    STRING_ID_ENTRY(global, smash_left), // 0x10C
    STRING_ID_ENTRY(global, smash_right), // 0x10D
    STRING_ID_ENTRY(global, mp_time), // 0x10E
    STRING_ID_ENTRY(global, team), // 0x10F
    STRING_ID_ENTRY(global, vault), // 0x110
    STRING_ID_ENTRY(global, press_a_to_join), // 0x111
    STRING_ID_ENTRY(global, easy), // 0x112
    STRING_ID_ENTRY(global, heroic), // 0x113
    STRING_ID_ENTRY(global, legendary), // 0x114
    STRING_ID_ENTRY(global, mute), // 0x115
    STRING_ID_ENTRY(global, unmute), // 0x116
    STRING_ID_ENTRY(global, boot_from_squad), // 0x117
    STRING_ID_ENTRY(global, revert_to_last_save), // 0x118
    STRING_ID_ENTRY(global, restart_level), // 0x119
    STRING_ID_ENTRY(global, save_and_quit), // 0x11A
    STRING_ID_ENTRY(global, spartan), // 0x11B
    STRING_ID_ENTRY(global, covenant), // 0x11C
    STRING_ID_ENTRY(global, voice_output), // 0x11D
    STRING_ID_ENTRY(global, 0), // 0x11E
    STRING_ID_ENTRY(global, 1), // 0x11F
    STRING_ID_ENTRY(global, 2), // 0x120
    STRING_ID_ENTRY(global, 3), // 0x121
    STRING_ID_ENTRY(global, 4), // 0x122
    STRING_ID_ENTRY(global, 5), // 0x123
    STRING_ID_ENTRY(global, 6), // 0x124
    STRING_ID_ENTRY(global, 7), // 0x125
    STRING_ID_ENTRY(global, 8), // 0x126
    STRING_ID_ENTRY(global, 9), // 0x127
    STRING_ID_ENTRY(global, 10), // 0x128
    STRING_ID_ENTRY(global, 11), // 0x129
    STRING_ID_ENTRY(global, 12), // 0x12A
    STRING_ID_ENTRY(global, 13), // 0x12B
    STRING_ID_ENTRY(global, 14), // 0x12C
    STRING_ID_ENTRY(global, 15), // 0x12D
    STRING_ID_ENTRY(global, 16), // 0x12E
    STRING_ID_ENTRY(global, 17), // 0x12F
    STRING_ID_ENTRY(global, 18), // 0x130
    STRING_ID_ENTRY(global, 19), // 0x131
    STRING_ID_ENTRY(global, 20), // 0x132
    STRING_ID_ENTRY(global, 21), // 0x133
    STRING_ID_ENTRY(global, 22), // 0x134
    STRING_ID_ENTRY(global, 23), // 0x135
    STRING_ID_ENTRY(global, 24), // 0x136
    STRING_ID_ENTRY(global, 25), // 0x137
    STRING_ID_ENTRY(global, 26), // 0x138
    STRING_ID_ENTRY(global, 27), // 0x139
    STRING_ID_ENTRY(global, 28), // 0x13A
    STRING_ID_ENTRY(global, 29), // 0x13B
    STRING_ID_ENTRY(global, 30), // 0x13C
    STRING_ID_ENTRY(global, 31), // 0x13D
    STRING_ID_ENTRY(global, 32), // 0x13E
    STRING_ID_ENTRY(global, 33), // 0x13F
    STRING_ID_ENTRY(global, 34), // 0x140
    STRING_ID_ENTRY(global, 35), // 0x141
    STRING_ID_ENTRY(global, 36), // 0x142
    STRING_ID_ENTRY(global, 37), // 0x143
    STRING_ID_ENTRY(global, 38), // 0x144
    STRING_ID_ENTRY(global, 39), // 0x145
    STRING_ID_ENTRY(global, 40), // 0x146
    STRING_ID_ENTRY(global, 41), // 0x147
    STRING_ID_ENTRY(global, 42), // 0x148
    STRING_ID_ENTRY(global, 43), // 0x149
    STRING_ID_ENTRY(global, 44), // 0x14A
    STRING_ID_ENTRY(global, 45), // 0x14B
    STRING_ID_ENTRY(global, 46), // 0x14C
    STRING_ID_ENTRY(global, 47), // 0x14D
    STRING_ID_ENTRY(global, 48), // 0x14E
    STRING_ID_ENTRY(global, 49), // 0x14F
    STRING_ID_ENTRY(global, 50), // 0x150
    STRING_ID_ENTRY(global, 51), // 0x151
    STRING_ID_ENTRY(global, 52), // 0x152
    STRING_ID_ENTRY(global, 53), // 0x153
    STRING_ID_ENTRY(global, 54), // 0x154
    STRING_ID_ENTRY(global, 55), // 0x155
    STRING_ID_ENTRY(global, 56), // 0x156
    STRING_ID_ENTRY(global, 57), // 0x157
    STRING_ID_ENTRY(global, 58), // 0x158
    STRING_ID_ENTRY(global, 59), // 0x159
    STRING_ID_ENTRY(global, 60), // 0x15A
    STRING_ID_ENTRY(global, 61), // 0x15B
    STRING_ID_ENTRY(global, 62), // 0x15C
    STRING_ID_ENTRY(global, 63), // 0x15D
    STRING_ID_ENTRY(global, 64), // 0x15E
    STRING_ID_ENTRY(global, 65), // 0x15F
    STRING_ID_ENTRY(global, 66), // 0x160
    STRING_ID_ENTRY(global, 67), // 0x161
    STRING_ID_ENTRY(global, 68), // 0x162
    STRING_ID_ENTRY(global, 69), // 0x163
    STRING_ID_ENTRY(global, 70), // 0x164
    STRING_ID_ENTRY(global, 71), // 0x165
    STRING_ID_ENTRY(global, 72), // 0x166
    STRING_ID_ENTRY(global, 73), // 0x167
    STRING_ID_ENTRY(global, 74), // 0x168
    STRING_ID_ENTRY(global, 75), // 0x169
    STRING_ID_ENTRY(global, 76), // 0x16A
    STRING_ID_ENTRY(global, 77), // 0x16B
    STRING_ID_ENTRY(global, 78), // 0x16C
    STRING_ID_ENTRY(global, 79), // 0x16D
    STRING_ID_ENTRY(global, 80), // 0x16E
    STRING_ID_ENTRY(global, 81), // 0x16F
    STRING_ID_ENTRY(global, 82), // 0x170
    STRING_ID_ENTRY(global, 83), // 0x171
    STRING_ID_ENTRY(global, 84), // 0x172
    STRING_ID_ENTRY(global, 85), // 0x173
    STRING_ID_ENTRY(global, 86), // 0x174
    STRING_ID_ENTRY(global, 87), // 0x175
    STRING_ID_ENTRY(global, 88), // 0x176
    STRING_ID_ENTRY(global, 89), // 0x177
    STRING_ID_ENTRY(global, 90), // 0x178
    STRING_ID_ENTRY(global, 91), // 0x179
    STRING_ID_ENTRY(global, 92), // 0x17A
    STRING_ID_ENTRY(global, 93), // 0x17B
    STRING_ID_ENTRY(global, 94), // 0x17C
    STRING_ID_ENTRY(global, 95), // 0x17D
    STRING_ID_ENTRY(global, 96), // 0x17E
    STRING_ID_ENTRY(global, 97), // 0x17F
    STRING_ID_ENTRY(global, 98), // 0x180
    STRING_ID_ENTRY(global, 99), // 0x181
    STRING_ID_ENTRY(global, 100), // 0x182
    STRING_ID_ENTRY(global, foreground0), // 0x183
    STRING_ID_ENTRY(global, foreground1), // 0x184
    STRING_ID_ENTRY(global, foreground2), // 0x185
    STRING_ID_ENTRY(global, foreground3), // 0x186
    STRING_ID_ENTRY(global, foreground4), // 0x187
    STRING_ID_ENTRY(global, foreground5), // 0x188
    STRING_ID_ENTRY(global, foreground6), // 0x189
    STRING_ID_ENTRY(global, foreground7), // 0x18A
    STRING_ID_ENTRY(global, foreground8), // 0x18B
    STRING_ID_ENTRY(global, foreground9), // 0x18C
    STRING_ID_ENTRY(global, foreground10), // 0x18D
    STRING_ID_ENTRY(global, foreground11), // 0x18E
    STRING_ID_ENTRY(global, foreground12), // 0x18F
    STRING_ID_ENTRY(global, foreground13), // 0x190
    STRING_ID_ENTRY(global, foreground14), // 0x191
    STRING_ID_ENTRY(global, foreground15), // 0x192
    STRING_ID_ENTRY(global, foreground16), // 0x193
    STRING_ID_ENTRY(global, foreground17), // 0x194
    STRING_ID_ENTRY(global, foreground18), // 0x195
    STRING_ID_ENTRY(global, foreground19), // 0x196
    STRING_ID_ENTRY(global, foreground20), // 0x197
    STRING_ID_ENTRY(global, foreground21), // 0x198
    STRING_ID_ENTRY(global, foreground22), // 0x199
    STRING_ID_ENTRY(global, foreground23), // 0x19A
    STRING_ID_ENTRY(global, foreground24), // 0x19B
    STRING_ID_ENTRY(global, foreground25), // 0x19C
    STRING_ID_ENTRY(global, foreground26), // 0x19D
    STRING_ID_ENTRY(global, foreground27), // 0x19E
    STRING_ID_ENTRY(global, foreground28), // 0x19F
    STRING_ID_ENTRY(global, foreground29), // 0x1A0
    STRING_ID_ENTRY(global, foreground30), // 0x1A1
    STRING_ID_ENTRY(global, foreground31), // 0x1A2
    STRING_ID_ENTRY(global, foreground32), // 0x1A3
    STRING_ID_ENTRY(global, foreground33), // 0x1A4
    STRING_ID_ENTRY(global, foreground34), // 0x1A5
    STRING_ID_ENTRY(global, foreground35), // 0x1A6
    STRING_ID_ENTRY(global, foreground36), // 0x1A7
    STRING_ID_ENTRY(global, foreground37), // 0x1A8
    STRING_ID_ENTRY(global, foreground38), // 0x1A9
    STRING_ID_ENTRY(global, foreground39), // 0x1AA
    STRING_ID_ENTRY(global, foreground40), // 0x1AB
    STRING_ID_ENTRY(global, foreground41), // 0x1AC
    STRING_ID_ENTRY(global, foreground42), // 0x1AD
    STRING_ID_ENTRY(global, foreground43), // 0x1AE
    STRING_ID_ENTRY(global, foreground44), // 0x1AF
    STRING_ID_ENTRY(global, foreground45), // 0x1B0
    STRING_ID_ENTRY(global, foreground46), // 0x1B1
    STRING_ID_ENTRY(global, foreground47), // 0x1B2
    STRING_ID_ENTRY(global, foreground48), // 0x1B3
    STRING_ID_ENTRY(global, foreground49), // 0x1B4
    STRING_ID_ENTRY(global, foreground50), // 0x1B5
    STRING_ID_ENTRY(global, foreground51), // 0x1B6
    STRING_ID_ENTRY(global, foreground52), // 0x1B7
    STRING_ID_ENTRY(global, foreground53), // 0x1B8
    STRING_ID_ENTRY(global, foreground54), // 0x1B9
    STRING_ID_ENTRY(global, foreground55), // 0x1BA
    STRING_ID_ENTRY(global, foreground56), // 0x1BB
    STRING_ID_ENTRY(global, foreground57), // 0x1BC
    STRING_ID_ENTRY(global, foreground58), // 0x1BD
    STRING_ID_ENTRY(global, foreground59), // 0x1BE
    STRING_ID_ENTRY(global, foreground60), // 0x1BF
    STRING_ID_ENTRY(global, foreground61), // 0x1C0
    STRING_ID_ENTRY(global, foreground62), // 0x1C1
    STRING_ID_ENTRY(global, foreground63), // 0x1C2
    STRING_ID_ENTRY(global, background0), // 0x1C3
    STRING_ID_ENTRY(global, background1), // 0x1C4
    STRING_ID_ENTRY(global, background2), // 0x1C5
    STRING_ID_ENTRY(global, background3), // 0x1C6
    STRING_ID_ENTRY(global, background4), // 0x1C7
    STRING_ID_ENTRY(global, background5), // 0x1C8
    STRING_ID_ENTRY(global, background6), // 0x1C9
    STRING_ID_ENTRY(global, background7), // 0x1CA
    STRING_ID_ENTRY(global, background8), // 0x1CB
    STRING_ID_ENTRY(global, background9), // 0x1CC
    STRING_ID_ENTRY(global, background10), // 0x1CD
    STRING_ID_ENTRY(global, background11), // 0x1CE
    STRING_ID_ENTRY(global, background12), // 0x1CF
    STRING_ID_ENTRY(global, background13), // 0x1D0
    STRING_ID_ENTRY(global, background14), // 0x1D1
    STRING_ID_ENTRY(global, background15), // 0x1D2
    STRING_ID_ENTRY(global, background16), // 0x1D3
    STRING_ID_ENTRY(global, background17), // 0x1D4
    STRING_ID_ENTRY(global, background18), // 0x1D5
    STRING_ID_ENTRY(global, background19), // 0x1D6
    STRING_ID_ENTRY(global, background20), // 0x1D7
    STRING_ID_ENTRY(global, background21), // 0x1D8
    STRING_ID_ENTRY(global, background22), // 0x1D9
    STRING_ID_ENTRY(global, background23), // 0x1DA
    STRING_ID_ENTRY(global, background24), // 0x1DB
    STRING_ID_ENTRY(global, background25), // 0x1DC
    STRING_ID_ENTRY(global, background26), // 0x1DD
    STRING_ID_ENTRY(global, background27), // 0x1DE
    STRING_ID_ENTRY(global, background28), // 0x1DF
    STRING_ID_ENTRY(global, background29), // 0x1E0
    STRING_ID_ENTRY(global, background30), // 0x1E1
    STRING_ID_ENTRY(global, background31), // 0x1E2
    STRING_ID_ENTRY(global, look_sensitivity), // 0x1E3
    STRING_ID_ENTRY(global, never), // 0x1E4
    STRING_ID_ENTRY(global, all), // 0x1E5
    STRING_ID_ENTRY(global, sniper), // 0x1E6
    STRING_ID_ENTRY(global, abdicate_leadership), // 0x1E7
    STRING_ID_ENTRY(global, content_download), // 0x1E8
    STRING_ID_ENTRY(global, walk_front), // 0x1E9
    STRING_ID_ENTRY(global, walk_back), // 0x1EA
    STRING_ID_ENTRY(global, walk_left), // 0x1EB
    STRING_ID_ENTRY(global, walk_right), // 0x1EC
    STRING_ID_ENTRY(global, default_material), // 0x1ED
    STRING_ID_ENTRY(global, hint_vault_step), // 0x1EE
    STRING_ID_ENTRY(global, hint_vault_crouch), // 0x1EF
    STRING_ID_ENTRY(global, hint_mount_step), // 0x1F0
    STRING_ID_ENTRY(global, hint_mount_crouch), // 0x1F1
    STRING_ID_ENTRY(global, hint_mount_stand), // 0x1F2
    STRING_ID_ENTRY(global, hint_hoist_crouch), // 0x1F3
    STRING_ID_ENTRY(global, hint_hoist_stand), // 0x1F4
    STRING_ID_ENTRY(global, physics_control), // 0x1F5
    STRING_ID_ENTRY(global, origin_marker), // 0x1F6
    STRING_ID_ENTRY(global, hoist), // 0x1F7
    STRING_ID_ENTRY(global, hoist_crouch), // 0x1F8
    STRING_ID_ENTRY(global, hoist_stand), // 0x1F9
    STRING_ID_ENTRY(global, disarm_left), // 0x1FA
    STRING_ID_ENTRY(global, drop_left), // 0x1FB
    STRING_ID_ENTRY(global, ready_left), // 0x1FC
    STRING_ID_ENTRY(global, ready_left_overheated), // 0x1FD
    STRING_ID_ENTRY(global, put_away_left), // 0x1FE
    STRING_ID_ENTRY(global, reload_1_left), // 0x1FF
    STRING_ID_ENTRY(global, reload_2_left), // 0x200
    STRING_ID_ENTRY(global, chamber_1_left), // 0x201
    STRING_ID_ENTRY(global, chamber_2_left), // 0x202
    STRING_ID_ENTRY(global, fire_1_left), // 0x203
    STRING_ID_ENTRY(global, fire_2_left), // 0x204
    STRING_ID_ENTRY(global, charged_1_left), // 0x205
    STRING_ID_ENTRY(global, charged_2_left), // 0x206
    STRING_ID_ENTRY(global, flight), // 0x207
    STRING_ID_ENTRY(global, takeoff), // 0x208
    STRING_ID_ENTRY(global, perch), // 0x209
    STRING_ID_ENTRY(global, perch_wall_left), // 0x20A
    STRING_ID_ENTRY(global, perch_wall_right), // 0x20B
    STRING_ID_ENTRY(global, perch_wall_ceiling), // 0x20C
    STRING_ID_ENTRY(global, l_clavicle), // 0x20D
    STRING_ID_ENTRY(global, l_upperarm), // 0x20E
    STRING_ID_ENTRY(global, arm_offsets), // 0x20F
    STRING_ID_ENTRY(global, dual), // 0x210
    STRING_ID_ENTRY(global, forward), // 0x211
    STRING_ID_ENTRY(global, replace), // 0x212
    STRING_ID_ENTRY(global, root), // 0x213
    STRING_ID_ENTRY(global, backward), // 0x214
    STRING_ID_ENTRY(global, constant_overlay), // 0x215
    STRING_ID_ENTRY(global, time), // 0x216
    STRING_ID_ENTRY(global, perch_wall_center), // 0x217
    STRING_ID_ENTRY(global, current_body_damage), // 0x218
    STRING_ID_ENTRY(global, current_shield_damage), // 0x219
    STRING_ID_ENTRY(global, body_vitality), // 0x21A
    STRING_ID_ENTRY(global, shield_vitality), // 0x21B
    STRING_ID_ENTRY(global, object_overshield_amount), // 0x21C
    STRING_ID_ENTRY(global, alive), // 0x21D
    STRING_ID_ENTRY(global, compass), // 0x21E
    STRING_ID_ENTRY(global, variant), // 0x21F
    STRING_ID_ENTRY(global, game_variant), // 0x220
    STRING_ID_ENTRY(global, map_variant), // 0x221
    STRING_ID_ENTRY(global, change_in_power), // 0x222
    STRING_ID_ENTRY(global, change_in_position), // 0x223
    STRING_ID_ENTRY(global, locked), // 0x224
    STRING_ID_ENTRY(global, delay), // 0x225
    STRING_ID_ENTRY(global, time_remaining), // 0x226
    STRING_ID_ENTRY(global, range_remaining), // 0x227
    STRING_ID_ENTRY(global, tracer), // 0x228
    STRING_ID_ENTRY(global, acceleration_range), // 0x229
    STRING_ID_ENTRY(global, projectile_attach), // 0x22A
    STRING_ID_ENTRY(global, heat), // 0x22B
    STRING_ID_ENTRY(global, turned_on), // 0x22C
    STRING_ID_ENTRY(global, turning_on), // 0x22D
    STRING_ID_ENTRY(global, illumination), // 0x22E
    STRING_ID_ENTRY(global, primary_ammunition), // 0x22F
    STRING_ID_ENTRY(global, primary_ammunition_ones), // 0x230
    STRING_ID_ENTRY(global, primary_ammunition_tens), // 0x231
    STRING_ID_ENTRY(global, secondary_ammunition), // 0x232
    STRING_ID_ENTRY(global, primary_ejection_port), // 0x233
    STRING_ID_ENTRY(global, secondary_ejection_port), // 0x234
    STRING_ID_ENTRY(global, primary_rate_of_fire), // 0x235
    STRING_ID_ENTRY(global, secondary_rate_of_fire), // 0x236
    STRING_ID_ENTRY(global, primary_firing), // 0x237
    STRING_ID_ENTRY(global, secondary_firing), // 0x238
    STRING_ID_ENTRY(global, primary_charged), // 0x239
    STRING_ID_ENTRY(global, secondary_charged), // 0x23A
    STRING_ID_ENTRY(global, age), // 0x23B
    STRING_ID_ENTRY(global, death), // 0x23C
    STRING_ID_ENTRY(global, primary_trigger_down), // 0x23D
    STRING_ID_ENTRY(global, secondary_trigger_down), // 0x23E
    STRING_ID_ENTRY(global, primary_barrel_firing), // 0x23F
    STRING_ID_ENTRY(global, secondary_barrel_firing), // 0x240
    STRING_ID_ENTRY(global, primary_barrel_firing_single), // 0x241
    STRING_ID_ENTRY(global, primary_barrel_firing_dual_left), // 0x242
    STRING_ID_ENTRY(global, primary_barrel_firing_dual_right), // 0x243
    STRING_ID_ENTRY(global, relaxation_poses), // 0x244
    STRING_ID_ENTRY(global, speed_absolute), // 0x245
    STRING_ID_ENTRY(global, jump), // 0x246
    STRING_ID_ENTRY(global, boost), // 0x247
    STRING_ID_ENTRY(global, left_tread_position), // 0x248
    STRING_ID_ENTRY(global, right_tread_position), // 0x249
    STRING_ID_ENTRY(global, left_tread_velocity), // 0x24A
    STRING_ID_ENTRY(global, right_tread_velocity), // 0x24B
    STRING_ID_ENTRY(global, front_left_tire_position), // 0x24C
    STRING_ID_ENTRY(global, front_right_tire_position), // 0x24D
    STRING_ID_ENTRY(global, back_left_tire_position), // 0x24E
    STRING_ID_ENTRY(global, back_right_tire_position), // 0x24F
    STRING_ID_ENTRY(global, front_left_tire_velocity), // 0x250
    STRING_ID_ENTRY(global, front_right_tire_velocity), // 0x251
    STRING_ID_ENTRY(global, back_left_tire_velocity), // 0x252
    STRING_ID_ENTRY(global, back_right_tire_velocity), // 0x253
    STRING_ID_ENTRY(global, wingtip_contrail), // 0x254
    STRING_ID_ENTRY(global, thrust), // 0x255
    STRING_ID_ENTRY(global, hover), // 0x256
    STRING_ID_ENTRY(global, engine_cruising), // 0x257
    STRING_ID_ENTRY(global, engine_rpm), // 0x258
    STRING_ID_ENTRY(global, wingtip_contrail_new), // 0x259
    STRING_ID_ENTRY(global, mean_antigrav), // 0x25A
    STRING_ID_ENTRY(global, driver_seat_power), // 0x25B
    STRING_ID_ENTRY(global, gunner_seat_power), // 0x25C
    STRING_ID_ENTRY(global, aiming_change), // 0x25D
    STRING_ID_ENTRY(global, horizontal_aiming_change), // 0x25E
    STRING_ID_ENTRY(global, mouth_aperture), // 0x25F
    STRING_ID_ENTRY(global, integrated_light_power), // 0x260
    STRING_ID_ENTRY(global, can_blink), // 0x261
    STRING_ID_ENTRY(global, driver_seat_occupied), // 0x262
    STRING_ID_ENTRY(global, gunner_seat_occupied), // 0x263
    STRING_ID_ENTRY(global, flying_speed), // 0x264
    STRING_ID_ENTRY(global, engine_power), // 0x265
    STRING_ID_ENTRY(global, engine_power_left), // 0x266
    STRING_ID_ENTRY(global, engine_power_right), // 0x267
    STRING_ID_ENTRY(global, one), // 0x268
    STRING_ID_ENTRY(global, zero), // 0x269
    STRING_ID_ENTRY(global, weapon_illumination), // 0x26A
    STRING_ID_ENTRY(global, weapon_battery_empty), // 0x26B
    STRING_ID_ENTRY(global, barrel_spin), // 0x26C
    STRING_ID_ENTRY(global, barrel_spin_rate), // 0x26D
    STRING_ID_ENTRY(global, random_constant), // 0x26E
    STRING_ID_ENTRY(global, loop), // 0x26F
    STRING_ID_ENTRY(global, shield_depleted), // 0x270
    STRING_ID_ENTRY(global, drop_right), // 0x271
    STRING_ID_ENTRY(global, reload_enter), // 0x272
    STRING_ID_ENTRY(global, reload_continue_empty), // 0x273
    STRING_ID_ENTRY(global, reload_continue_full), // 0x274
    STRING_ID_ENTRY(global, reload_exit), // 0x275
    STRING_ID_ENTRY(global, melee_lunge), // 0x276
    STRING_ID_ENTRY(global, melee_lunge_airborne), // 0x277
    STRING_ID_ENTRY(global, melee_lunge_unaimed), // 0x278
    STRING_ID_ENTRY(global, melee_lunge_unaimed_airborne), // 0x279
    STRING_ID_ENTRY(global, infection_front), // 0x27A
    STRING_ID_ENTRY(global, infection_back), // 0x27B
    STRING_ID_ENTRY(global, infect), // 0x27C
    STRING_ID_ENTRY(global, thrash_front), // 0x27D
    STRING_ID_ENTRY(global, thrash_back), // 0x27E
    STRING_ID_ENTRY(global, infection_wrestle), // 0x27F
    STRING_ID_ENTRY(global, infection_start), // 0x280
    STRING_ID_ENTRY(global, melee_back), // 0x281
    STRING_ID_ENTRY(global, melee_left), // 0x282
    STRING_ID_ENTRY(global, melee_right), // 0x283
    STRING_ID_ENTRY(global, infection_spew), // 0x284
    STRING_ID_ENTRY(global, pelvis), // 0x285
    STRING_ID_ENTRY(global, melee_dash), // 0x286
    STRING_ID_ENTRY(global, melee_dash_airborne), // 0x287
    STRING_ID_ENTRY(global, bumper), // 0x288
    STRING_ID_ENTRY(global, splitscreen_coop), // 0x289
    STRING_ID_ENTRY(global, splitscreen_custom), // 0x28A
    STRING_ID_ENTRY(global, system_link_coop), // 0x28B
    STRING_ID_ENTRY(global, system_link_custom), // 0x28C
    STRING_ID_ENTRY(global, live_coop), // 0x28D
    STRING_ID_ENTRY(global, live_custom), // 0x28E
    STRING_ID_ENTRY(global, live_optimatch), // 0x28F
    STRING_ID_ENTRY(global, ground_speed_rear), // 0x290
    STRING_ID_ENTRY(global, hud_wp_os_amt), // 0x291
    STRING_ID_ENTRY(global, hud_wp_alpha), // 0x292
    STRING_ID_ENTRY(global, hud_wp_theta), // 0x293
    STRING_ID_ENTRY(global, hud_wp_arrow_t), // 0x294
    STRING_ID_ENTRY(global, hud_elite), // 0x295
    STRING_ID_ENTRY(global, hud_input1), // 0x296
    STRING_ID_ENTRY(global, hud_input2), // 0x297
    STRING_ID_ENTRY(global, hud_input3), // 0x298
    STRING_ID_ENTRY(global, hud_input4), // 0x299
    STRING_ID_ENTRY(global, map), // 0x29A
    STRING_ID_ENTRY(global, level), // 0x29B
    STRING_ID_ENTRY(global, difficulty), // 0x29C
    STRING_ID_ENTRY(global, hopper), // 0x29D
    STRING_ID_ENTRY(global, emblem_active), // 0x29E
    STRING_ID_ENTRY(global, emblem_foreground_index), // 0x29F
    STRING_ID_ENTRY(global, emblem_background_index), // 0x2A0
    STRING_ID_ENTRY(global, emblem_alternate_foreground_enabled), // 0x2A1
    STRING_ID_ENTRY(global, emblem_flip_foreground_image), // 0x2A2
    STRING_ID_ENTRY(global, emblem_flip_background_image), // 0x2A3
    STRING_ID_ENTRY(global, emblem_primary_color_index), // 0x2A4
    STRING_ID_ENTRY(global, emblem_secondary_color_index), // 0x2A5
    STRING_ID_ENTRY(global, emblem_background_color_index), // 0x2A6
    STRING_ID_ENTRY(global, melee_strike_1), // 0x2A7
    STRING_ID_ENTRY(global, melee_strike_2), // 0x2A8
    STRING_ID_ENTRY(global, melee_strike_3), // 0x2A9
    STRING_ID_ENTRY(global, melee_strike_4), // 0x2AA
    STRING_ID_ENTRY(global, grip), // 0x2AB
    STRING_ID_ENTRY(global, dth), // 0x2AC
    STRING_ID_ENTRY(global, dth_mjr), // 0x2AD
    STRING_ID_ENTRY(global, dth_slw), // 0x2AE
    STRING_ID_ENTRY(global, dth_hdsht), // 0x2AF
    STRING_ID_ENTRY(global, dth_slnt), // 0x2B0
    STRING_ID_ENTRY(global, dth_fall), // 0x2B1
    STRING_ID_ENTRY(global, dth_drama), // 0x2B2
    STRING_ID_ENTRY(global, dth_reanimated), // 0x2B3
    STRING_ID_ENTRY(global, pain_mdm), // 0x2B4
    STRING_ID_ENTRY(global, pain_mjr), // 0x2B5
    STRING_ID_ENTRY(global, pain_shld), // 0x2B6
    STRING_ID_ENTRY(global, pain_fall), // 0x2B7
    STRING_ID_ENTRY(global, cower), // 0x2B8
    STRING_ID_ENTRY(global, fall), // 0x2B9
    STRING_ID_ENTRY(global, srprs), // 0x2BA
    STRING_ID_ENTRY(global, emitter), // 0x2BB
    STRING_ID_ENTRY(global, emitting), // 0x2BC
    STRING_ID_ENTRY(global, enter_a), // 0x2BD
    STRING_ID_ENTRY(global, enter_b), // 0x2BE
    STRING_ID_ENTRY(global, enter_c), // 0x2BF
    STRING_ID_ENTRY(global, enter_d), // 0x2C0
    STRING_ID_ENTRY(global, melee_off_hand), // 0x2C1
    STRING_ID_ENTRY(global, overheating_left), // 0x2C2
    STRING_ID_ENTRY(global, overheated_left), // 0x2C3
    STRING_ID_ENTRY(global, o_h_exit_left), // 0x2C4
    STRING_ID_ENTRY(global, name), // 0x2C5
    STRING_ID_ENTRY(global, title), // 0x2C6
    STRING_ID_ENTRY(global, description), // 0x2C7
    STRING_ID_ENTRY(global, eye_trigger), // 0x2C8
    STRING_ID_ENTRY(global, needler_trigger), // 0x2C9
    STRING_ID_ENTRY(global, rocket_trigger), // 0x2CA
    STRING_ID_ENTRY(global, one_way), // 0x2CB
    STRING_ID_ENTRY(global, warn_leave_party), // 0x2CC
    STRING_ID_ENTRY(global, cancel_leave_party), // 0x2CD
    STRING_ID_ENTRY(global, proceed_leave_party), // 0x2CE
    STRING_ID_ENTRY(global, warn_bring_party), // 0x2CF
    STRING_ID_ENTRY(global, cancel_bring_party), // 0x2D0
    STRING_ID_ENTRY(global, proceed_bring_party), // 0x2D1
    STRING_ID_ENTRY(global, dont_bring_party), // 0x2D2
    STRING_ID_ENTRY(global, phantom_speed), // 0x2D3
    STRING_ID_ENTRY(global, phantom_power), // 0x2D4
    STRING_ID_ENTRY(global, phantom_on), // 0x2D5
    STRING_ID_ENTRY(global, jetpack_exhaust), // 0x2D6
    STRING_ID_ENTRY(global, player_name), // 0x2D7
    STRING_ID_ENTRY(global, land), // 0x2D8
    STRING_ID_ENTRY(global, random_seed_1), // 0x2D9
    STRING_ID_ENTRY(global, random_seed_2), // 0x2DA
    STRING_ID_ENTRY(global, random_seed_3), // 0x2DB
    STRING_ID_ENTRY(global, random_seed_4), // 0x2DC
    STRING_ID_ENTRY(global, unique_id), // 0x2DD
    STRING_ID_ENTRY(global, hud_autosave_begin), // 0x2DE
    STRING_ID_ENTRY(global, hud_autosave_end), // 0x2DF
    STRING_ID_ENTRY(global, hud_loading_begin), // 0x2E0
    STRING_ID_ENTRY(global, hud_loading_end), // 0x2E1
    STRING_ID_ENTRY(global, hud_saving_begin), // 0x2E2
    STRING_ID_ENTRY(global, hud_saving_end), // 0x2E3
    STRING_ID_ENTRY(global, hud_respawn_faliure_combat), // 0x2E4
    STRING_ID_ENTRY(global, hud_respawn_faliure_unsafe), // 0x2E5
    STRING_ID_ENTRY(global, hud_respawn_faliure_moving), // 0x2E6
    STRING_ID_ENTRY(global, hud_respawn_faliure_vehicle), // 0x2E7
    STRING_ID_ENTRY(global, unit_open), // 0x2E8
    STRING_ID_ENTRY(global, unit_closed), // 0x2E9
    STRING_ID_ENTRY(global, deploy), // 0x2EA
    STRING_ID_ENTRY(global, vehicle_root), // 0x2EB
    STRING_ID_ENTRY(global, leap_land), // 0x2EC
    STRING_ID_ENTRY(global, melee_flurry), // 0x2ED
    STRING_ID_ENTRY(global, electrical_power), // 0x2EE
    STRING_ID_ENTRY(global, all_quiet), // 0x2EF
    STRING_ID_ENTRY(global, time_hours), // 0x2F0
    STRING_ID_ENTRY(global, time_minutes), // 0x2F1
    STRING_ID_ENTRY(global, time_seconds), // 0x2F2
    STRING_ID_ENTRY(global, morse_code), // 0x2F3
    STRING_ID_ENTRY(global, holiday), // 0x2F4
    STRING_ID_ENTRY(global, flashlights_allowed), // 0x2F5
    STRING_ID_ENTRY(global, vertical_thrust), // 0x2F6
    STRING_ID_ENTRY(global, hint_corner_left), // 0x2F7
    STRING_ID_ENTRY(global, hint_corner_right), // 0x2F8
    STRING_ID_ENTRY(global, hint_bunker), // 0x2F9
    STRING_ID_ENTRY(global, bunker_cover), // 0x2FA
    STRING_ID_ENTRY(global, bunker_open), // 0x2FB
    STRING_ID_ENTRY(global, ge_territories_territory_0), // 0x2FC
    STRING_ID_ENTRY(global, ge_territories_territory_1), // 0x2FD
    STRING_ID_ENTRY(global, ge_territories_territory_2), // 0x2FE
    STRING_ID_ENTRY(global, ge_territories_territory_3), // 0x2FF
    STRING_ID_ENTRY(global, ge_territories_territory_4), // 0x300
    STRING_ID_ENTRY(global, ge_territories_territory_5), // 0x301
    STRING_ID_ENTRY(global, ge_territories_territory_6), // 0x302
    STRING_ID_ENTRY(global, ge_territories_territory_7), // 0x303
    STRING_ID_ENTRY(global, melee_tackle), // 0x304
    STRING_ID_ENTRY(global, a_select_b_cancel), // 0x305
    STRING_ID_ENTRY(global, bomb_arming_amount), // 0x306
    STRING_ID_ENTRY(global, bomb_is_unarmed), // 0x307
    STRING_ID_ENTRY(global, bomb_is_arming), // 0x308
    STRING_ID_ENTRY(global, bomb_is_armed), // 0x309
    STRING_ID_ENTRY(global, unlocked_extra_1), // 0x30A
    STRING_ID_ENTRY(global, unlocked_extra_2), // 0x30B
    STRING_ID_ENTRY(global, unlocked_extra_3), // 0x30C
    STRING_ID_ENTRY(global, unlocked_extra_4), // 0x30D
    STRING_ID_ENTRY(global, unlocked_extra_5), // 0x30E
    STRING_ID_ENTRY(global, unlocked_extra_6), // 0x30F
    STRING_ID_ENTRY(global, unlocked_extra_7), // 0x310
    STRING_ID_ENTRY(global, unlocked_extra_8), // 0x311
    STRING_ID_ENTRY(global, unlocked_extra_9), // 0x312
    STRING_ID_ENTRY(global, unlocked_extra_10), // 0x313
    STRING_ID_ENTRY(global, unlocked_extra_11), // 0x314
    STRING_ID_ENTRY(global, unlocked_extra_12), // 0x315
    STRING_ID_ENTRY(global, unlocked_extra_13), // 0x316
    STRING_ID_ENTRY(global, unlocked_extra_14), // 0x317
    STRING_ID_ENTRY(global, locked_description), // 0x318
    STRING_ID_ENTRY(global, almost_never), // 0x319
    STRING_ID_ENTRY(global, rarely), // 0x31A
    STRING_ID_ENTRY(global, somewhat), // 0x31B
    STRING_ID_ENTRY(global, often), // 0x31C
    STRING_ID_ENTRY(global, always), // 0x31D
    STRING_ID_ENTRY(global, wildcard), // 0x31E
    STRING_ID_ENTRY(global, tread_grind), // 0x31F
    STRING_ID_ENTRY(global, anti_gravity_strength), // 0x320
    STRING_ID_ENTRY(global, anti_gravity_engine_position), // 0x321
    STRING_ID_ENTRY(global, scripted_object_function_a), // 0x322
    STRING_ID_ENTRY(global, scripted_object_function_b), // 0x323
    STRING_ID_ENTRY(global, scripted_object_function_c), // 0x324
    STRING_ID_ENTRY(global, scripted_object_function_d), // 0x325
    STRING_ID_ENTRY(global, missile), // 0x326
    STRING_ID_ENTRY(global, support), // 0x327
    STRING_ID_ENTRY(global, rifle), // 0x328
    STRING_ID_ENTRY(global, pistol), // 0x329
    STRING_ID_ENTRY(global, sword), // 0x32A
    STRING_ID_ENTRY(global, shake_fist), // 0x32B
    STRING_ID_ENTRY(global, cheer), // 0x32C
    STRING_ID_ENTRY(global, taunt), // 0x32D
    STRING_ID_ENTRY(global, brace), // 0x32E
    STRING_ID_ENTRY(global, point), // 0x32F
    STRING_ID_ENTRY(global, hold), // 0x330
    STRING_ID_ENTRY(global, wave), // 0x331
    STRING_ID_ENTRY(global, advance), // 0x332
    STRING_ID_ENTRY(global, fallback), // 0x333
    STRING_ID_ENTRY(global, english), // 0x334
    STRING_ID_ENTRY(global, japanese), // 0x335
    STRING_ID_ENTRY(global, german), // 0x336
    STRING_ID_ENTRY(global, french), // 0x337
    STRING_ID_ENTRY(global, spanish), // 0x338
    STRING_ID_ENTRY(global, mexican), // 0x339
    STRING_ID_ENTRY(global, italian), // 0x33A
    STRING_ID_ENTRY(global, korean), // 0x33B
    STRING_ID_ENTRY(global, chinese), // 0x33C
    STRING_ID_ENTRY(global, portuguese), // 0x33D
    STRING_ID_ENTRY(global, polish), // 0x33E
    STRING_ID_ENTRY(global, brsrk), // 0x33F
    STRING_ID_ENTRY(global, shakefist), // 0x340
    STRING_ID_ENTRY(global, variant_ctf), // 0x341
    STRING_ID_ENTRY(global, variant_ctf_description), // 0x342
    STRING_ID_ENTRY(global, variant_slayer), // 0x343
    STRING_ID_ENTRY(global, variant_slayer_description), // 0x344
    STRING_ID_ENTRY(global, variant_oddball), // 0x345
    STRING_ID_ENTRY(global, variant_oddball_description), // 0x346
    STRING_ID_ENTRY(global, variant_king), // 0x347
    STRING_ID_ENTRY(global, variant_king_description), // 0x348
    STRING_ID_ENTRY(global, variant_juggernaut), // 0x349
    STRING_ID_ENTRY(global, variant_juggernaut_description), // 0x34A
    STRING_ID_ENTRY(global, variant_territories), // 0x34B
    STRING_ID_ENTRY(global, variant_territories_description), // 0x34C
    STRING_ID_ENTRY(global, variant_assault), // 0x34D
    STRING_ID_ENTRY(global, variant_assault_description), // 0x34E
    STRING_ID_ENTRY(global, variant_infection), // 0x34F
    STRING_ID_ENTRY(global, variant_infection_description), // 0x350
    STRING_ID_ENTRY(global, variant_vip), // 0x351
    STRING_ID_ENTRY(global, variant_vip_description), // 0x352
    STRING_ID_ENTRY(global, variant_sandbox), // 0x353
    STRING_ID_ENTRY(global, variant_sandbox_description), // 0x354
    STRING_ID_ENTRY(global, meleeleap), // 0x355
    STRING_ID_ENTRY(global, pstcmbt), // 0x356
    STRING_ID_ENTRY(global, multiplayer), // 0x357
    STRING_ID_ENTRY(global, right_hand), // 0x358
    STRING_ID_ENTRY(global, l_thruster_target), // 0x359
    STRING_ID_ENTRY(global, r_thruster_target), // 0x35A
    STRING_ID_ENTRY(global, reanimate), // 0x35B
    STRING_ID_ENTRY(global, secret), // 0x35C
    STRING_ID_ENTRY(global, network_unknown), // 0x35D
    STRING_ID_ENTRY(global, network_loading_map), // 0x35E
    STRING_ID_ENTRY(global, network_running), // 0x35F
    STRING_ID_ENTRY(global, network_connecting), // 0x360
    STRING_ID_ENTRY(global, network_joining), // 0x361
    STRING_ID_ENTRY(global, network_reestablishing), // 0x362
    STRING_ID_ENTRY(global, network_leaving), // 0x363
    STRING_ID_ENTRY(global, warthog_chaingun_illumination), // 0x364
    STRING_ID_ENTRY(global, pause), // 0x365
    STRING_ID_ENTRY(global, stationary_march), // 0x366
    STRING_ID_ENTRY(global, turn_left_45), // 0x367
    STRING_ID_ENTRY(global, turn_right_45), // 0x368
    STRING_ID_ENTRY(global, move_front_turn_left_45), // 0x369
    STRING_ID_ENTRY(global, move_front_turn_right_45), // 0x36A
    STRING_ID_ENTRY(global, move_back_turn_left_45), // 0x36B
    STRING_ID_ENTRY(global, move_back_turn_right_45), // 0x36C
    STRING_ID_ENTRY(global, move_left_turn_left_45), // 0x36D
    STRING_ID_ENTRY(global, move_left_turn_right_45), // 0x36E
    STRING_ID_ENTRY(global, move_right_turn_left_45), // 0x36F
    STRING_ID_ENTRY(global, move_right_turn_right_45), // 0x370
    STRING_ID_ENTRY(global, buckle), // 0x371
    STRING_ID_ENTRY(global, buckle_wobble), // 0x372
    STRING_ID_ENTRY(global, belly), // 0x373
    STRING_ID_ENTRY(global, from_stalker), // 0x374
    STRING_ID_ENTRY(global, to_stalker), // 0x375
    STRING_ID_ENTRY(global, from_ranged), // 0x376
    STRING_ID_ENTRY(global, to_ranged), // 0x377
    STRING_ID_ENTRY(global, from_tank), // 0x378
    STRING_ID_ENTRY(global, to_tank), // 0x379
    STRING_ID_ENTRY(global, morph), // 0x37A
    STRING_ID_ENTRY(global, morph_arrival), // 0x37B
    STRING_ID_ENTRY(global, scorpion), // 0x37C
    STRING_ID_ENTRY(global, ghost), // 0x37D
    STRING_ID_ENTRY(global, warthog), // 0x37E
    STRING_ID_ENTRY(global, spectre), // 0x37F
    STRING_ID_ENTRY(global, wraith), // 0x380
    STRING_ID_ENTRY(global, phantom), // 0x381
    STRING_ID_ENTRY(global, pelican), // 0x382
    STRING_ID_ENTRY(global, banshee), // 0x383
    STRING_ID_ENTRY(global, vtol), // 0x384
    STRING_ID_ENTRY(global, hornet), // 0x385
    STRING_ID_ENTRY(global, chopper), // 0x386
    STRING_ID_ENTRY(global, mauler), // 0x387
    STRING_ID_ENTRY(global, mongoose), // 0x388
    STRING_ID_ENTRY(global, airborne_open), // 0x389
    STRING_ID_ENTRY(global, airborne_closed), // 0x38A
    STRING_ID_ENTRY(global, anticipate), // 0x38B
    STRING_ID_ENTRY(global, recover), // 0x38C
    STRING_ID_ENTRY(global, surge), // 0x38D
    STRING_ID_ENTRY(global, phase), // 0x38E
    STRING_ID_ENTRY(global, left_foot), // 0x38F
    STRING_ID_ENTRY(global, right_foot), // 0x390
    STRING_ID_ENTRY(global, stand), // 0x391
    STRING_ID_ENTRY(global, corner), // 0x392
    STRING_ID_ENTRY(global, corner_open), // 0x393
    STRING_ID_ENTRY(global, bunker), // 0x394
    STRING_ID_ENTRY(global, backup), // 0x395
    STRING_ID_ENTRY(global, guard), // 0x396
    STRING_ID_ENTRY(global, guard_crouch), // 0x397
    STRING_ID_ENTRY(global, guard_wall), // 0x398
    STRING_ID_ENTRY(global, kneel), // 0x399
    STRING_ID_ENTRY(global, gaze), // 0x39A
    STRING_ID_ENTRY(global, poke), // 0x39B
    STRING_ID_ENTRY(global, watch), // 0x39C
    STRING_ID_ENTRY(global, examine), // 0x39D
    STRING_ID_ENTRY(global, sleep), // 0x39E
    STRING_ID_ENTRY(global, at_ease), // 0x39F
    STRING_ID_ENTRY(global, tai_chi), // 0x3A0
    STRING_ID_ENTRY(global, pee), // 0x3A1
    STRING_ID_ENTRY(global, doze), // 0x3A2
    STRING_ID_ENTRY(global, eat), // 0x3A3
    STRING_ID_ENTRY(global, cheering), // 0x3A4
    STRING_ID_ENTRY(global, injured), // 0x3A5
    STRING_ID_ENTRY(global, captured), // 0x3A6
    STRING_ID_ENTRY(global, rest_1), // 0x3A7
    STRING_ID_ENTRY(global, rest_2), // 0x3A8
    STRING_ID_ENTRY(global, rest_3), // 0x3A9
    STRING_ID_ENTRY(global, rest_4), // 0x3AA
    STRING_ID_ENTRY(global, act_guard_1), // 0x3AB
    STRING_ID_ENTRY(global, act_guard_2), // 0x3AC
    STRING_ID_ENTRY(global, act_guard_3), // 0x3AD
    STRING_ID_ENTRY(global, act_guard_4), // 0x3AE
    STRING_ID_ENTRY(global, act_guard_crouch_1), // 0x3AF
    STRING_ID_ENTRY(global, act_guard_wall_1), // 0x3B0
    STRING_ID_ENTRY(global, act_kneel_1), // 0x3B1
    STRING_ID_ENTRY(global, act_kneel_2), // 0x3B2
    STRING_ID_ENTRY(global, act_kneel_3), // 0x3B3
    STRING_ID_ENTRY(global, act_kneel_4), // 0x3B4
    STRING_ID_ENTRY(global, act_injured_ankle), // 0x3B5
    STRING_ID_ENTRY(global, act_injured_sit_wall), // 0x3B6
    STRING_ID_ENTRY(global, act_injured_shoulder), // 0x3B7
    STRING_ID_ENTRY(global, act_injured_gut), // 0x3B8
    STRING_ID_ENTRY(global, act_smoking), // 0x3B9
    STRING_ID_ENTRY(global, act_cards), // 0x3BA
    STRING_ID_ENTRY(global, act_cower_1), // 0x3BB
    STRING_ID_ENTRY(global, act_cower_2), // 0x3BC
    STRING_ID_ENTRY(global, act_tai_chi), // 0x3BD
    STRING_ID_ENTRY(global, act_backup_left), // 0x3BE
    STRING_ID_ENTRY(global, act_backup_right), // 0x3BF
    STRING_ID_ENTRY(global, act_combat), // 0x3C0
    STRING_ID_ENTRY(global, act_cheering_1), // 0x3C1
    STRING_ID_ENTRY(global, act_cheering_2), // 0x3C2
    STRING_ID_ENTRY(global, act_cheering_3), // 0x3C3
    STRING_ID_ENTRY(global, act_cheering_4), // 0x3C4
    STRING_ID_ENTRY(global, act_cheering_5), // 0x3C5
    STRING_ID_ENTRY(global, act_eat_1), // 0x3C6
    STRING_ID_ENTRY(global, act_doze_sit_1), // 0x3C7
    STRING_ID_ENTRY(global, act_doze_stand_1), // 0x3C8
    STRING_ID_ENTRY(global, act_pee_1), // 0x3C9
    STRING_ID_ENTRY(global, act_examine_1), // 0x3CA
    STRING_ID_ENTRY(global, act_watch_1), // 0x3CB
    STRING_ID_ENTRY(global, act_track_1), // 0x3CC
    STRING_ID_ENTRY(global, act_sniff_1), // 0x3CD
    STRING_ID_ENTRY(global, act_poke_1), // 0x3CE
    STRING_ID_ENTRY(global, act_gaze_1), // 0x3CF
    STRING_ID_ENTRY(global, act_gaze_2), // 0x3D0
    STRING_ID_ENTRY(global, act_captured_1), // 0x3D1
    STRING_ID_ENTRY(global, act_captured_sit_wall), // 0x3D2
    STRING_ID_ENTRY(global, arbiter), // 0x3D3
    STRING_ID_ENTRY(global, oddball_effect), // 0x3D4
    STRING_ID_ENTRY(global, date_format_days_hours_minutes_seconds), // 0x3D5
    STRING_ID_ENTRY(global, date_format_hours_minutes_seconds), // 0x3D6
    STRING_ID_ENTRY(global, date_format_minutes_seconds), // 0x3D7
    STRING_ID_ENTRY(global, date_format_seconds), // 0x3D8
    STRING_ID_ENTRY(global, chud_out_a), // 0x3D9
    STRING_ID_ENTRY(global, chud_out_b), // 0x3DA
    STRING_ID_ENTRY(global, chud_out_c), // 0x3DB
    STRING_ID_ENTRY(global, chud_out_d), // 0x3DC
    STRING_ID_ENTRY(global, chud_out_e), // 0x3DD
    STRING_ID_ENTRY(global, chud_out_f), // 0x3DE
    STRING_ID_ENTRY(global, chud_variant_name), // 0x3DF
    STRING_ID_ENTRY(global, chud_talking_player_name), // 0x3E0
    STRING_ID_ENTRY(global, chud_arming_meter_name), // 0x3E1
    STRING_ID_ENTRY(global, chud_time_left), // 0x3E2
    STRING_ID_ENTRY(global, chud_training_text), // 0x3E3
    STRING_ID_ENTRY(global, texture), // 0x3E4
    STRING_ID_ENTRY(global, aim), // 0x3E5
    STRING_ID_ENTRY(global, stowed), // 0x3E6
    STRING_ID_ENTRY(global, draw_wpn_fast), // 0x3E7
    STRING_ID_ENTRY(global, draw_wpn_slow), // 0x3E8
    STRING_ID_ENTRY(global, facial_animation_base), // 0x3E9
    STRING_ID_ENTRY(global, facial_animation_overlay), // 0x3EA
    STRING_ID_ENTRY(global, neutral), // 0x3EB
    STRING_ID_ENTRY(global, happy), // 0x3EC
    STRING_ID_ENTRY(global, sad), // 0x3ED
    STRING_ID_ENTRY(global, angry), // 0x3EE
    STRING_ID_ENTRY(global, disgusted), // 0x3EF
    STRING_ID_ENTRY(global, scared), // 0x3F0
    STRING_ID_ENTRY(global, surprised), // 0x3F1
    STRING_ID_ENTRY(global, pain), // 0x3F2
    STRING_ID_ENTRY(global, all_gametypes), // 0x3F3
    STRING_ID_ENTRY(global, airborne_arc), // 0x3F4
    STRING_ID_ENTRY(global, airborne_overlay), // 0x3F5
    STRING_ID_ENTRY(global, lift), // 0x3F6
    STRING_ID_ENTRY(global, dive), // 0x3F7
    STRING_ID_ENTRY(global, dodge), // 0x3F8
    STRING_ID_ENTRY(global, bump), // 0x3F9
    STRING_ID_ENTRY(global, stun), // 0x3FA
    STRING_ID_ENTRY(global, charge), // 0x3FB
    STRING_ID_ENTRY(global, kamikaze), // 0x3FC
    STRING_ID_ENTRY(global, sigh), // 0x3FD
    STRING_ID_ENTRY(global, contempt), // 0x3FE
    STRING_ID_ENTRY(global, anger), // 0x3FF
    STRING_ID_ENTRY(global, fear), // 0x400
    STRING_ID_ENTRY(global, relief), // 0x401
    STRING_ID_ENTRY(global, terminal_error), // 0x402
    STRING_ID_ENTRY(global, activation), // 0x403
    STRING_ID_ENTRY(global, layer0_x), // 0x404
    STRING_ID_ENTRY(global, layer0_y), // 0x405
    STRING_ID_ENTRY(global, layer1_x), // 0x406
    STRING_ID_ENTRY(global, layer1_y), // 0x407
    STRING_ID_ENTRY(global, hex_intensity), // 0x408
    STRING_ID_ENTRY(global, overlay_intensity), // 0x409
    STRING_ID_ENTRY(global, reading_mode), // 0x40A
    STRING_ID_ENTRY(global, image), // 0x40B
    STRING_ID_ENTRY(global, count), // 0x40C
    STRING_ID_ENTRY(global, falling_damage), // 0x40D
    STRING_ID_ENTRY(global, collision_damage), // 0x40E
    STRING_ID_ENTRY(global, explosion), // 0x40F
    STRING_ID_ENTRY(global, magnum_pistol), // 0x410
    STRING_ID_ENTRY(global, plasma_pistol), // 0x411
    STRING_ID_ENTRY(global, needler), // 0x412
    STRING_ID_ENTRY(global, excavator), // 0x413
    STRING_ID_ENTRY(global, smg), // 0x414
    STRING_ID_ENTRY(global, plasma_rifle), // 0x415
    STRING_ID_ENTRY(global, battle_rifle), // 0x416
    STRING_ID_ENTRY(global, carbine), // 0x417
    STRING_ID_ENTRY(global, shotgun), // 0x418
    STRING_ID_ENTRY(global, sniper_rifle), // 0x419
    STRING_ID_ENTRY(global, beam_rifle), // 0x41A
    STRING_ID_ENTRY(global, assault_rifle), // 0x41B
    STRING_ID_ENTRY(global, spike_rifle), // 0x41C
    STRING_ID_ENTRY(global, flak_cannon), // 0x41D
    STRING_ID_ENTRY(global, missile_launcher), // 0x41E
    STRING_ID_ENTRY(global, rocket_launcher), // 0x41F
    STRING_ID_ENTRY(global, spartan_laser), // 0x420
    STRING_ID_ENTRY(global, brute_shot), // 0x421
    STRING_ID_ENTRY(global, flame_thrower), // 0x422
    STRING_ID_ENTRY(global, sentinel_gun), // 0x423
    STRING_ID_ENTRY(global, energy_blade), // 0x424
    STRING_ID_ENTRY(global, gravity_hammer), // 0x425
    STRING_ID_ENTRY(global, damage_frag_grenade), // 0x426
    STRING_ID_ENTRY(global, damage_plasma_grenade), // 0x427
    STRING_ID_ENTRY(global, claymore_grenade), // 0x428
    STRING_ID_ENTRY(global, firebomb_grenade), // 0x429
    STRING_ID_ENTRY(global, flag), // 0x42A
    STRING_ID_ENTRY(global, bomb), // 0x42B
    STRING_ID_ENTRY(global, bomb_explosion), // 0x42C
    STRING_ID_ENTRY(global, ball), // 0x42D
    STRING_ID_ENTRY(global, human_turret), // 0x42E
    STRING_ID_ENTRY(global, plasma_cannon), // 0x42F
    STRING_ID_ENTRY(global, plasma_mortar), // 0x430
    STRING_ID_ENTRY(global, plasma_turret), // 0x431
    STRING_ID_ENTRY(global, spectre_driver), // 0x432
    STRING_ID_ENTRY(global, spectre_gunner), // 0x433
    STRING_ID_ENTRY(global, warthog_driver), // 0x434
    STRING_ID_ENTRY(global, warthog_gunner), // 0x435
    STRING_ID_ENTRY(global, wraith_antiinfantry), // 0x436
    STRING_ID_ENTRY(global, tank), // 0x437
    STRING_ID_ENTRY(global, scorpion_gunner), // 0x438
    STRING_ID_ENTRY(global, mantis), // 0x439
    STRING_ID_ENTRY(global, sentinel_beam), // 0x43A
    STRING_ID_ENTRY(global, sentinel_rpg), // 0x43B
    STRING_ID_ENTRY(global, teleporter), // 0x43C
    STRING_ID_ENTRY(global, proximity_mine), // 0x43D
    STRING_ID_ENTRY(global, medal_image), // 0x43E
    STRING_ID_ENTRY(global, medal_name), // 0x43F
    STRING_ID_ENTRY(global, medal_description), // 0x440
    STRING_ID_ENTRY(global, extermination), // 0x441
    STRING_ID_ENTRY(global, perfection), // 0x442
    STRING_ID_ENTRY(global, multiple_kill_2), // 0x443
    STRING_ID_ENTRY(global, multiple_kill_3), // 0x444
    STRING_ID_ENTRY(global, multiple_kill_4), // 0x445
    STRING_ID_ENTRY(global, multiple_kill_5), // 0x446
    STRING_ID_ENTRY(global, multiple_kill_6), // 0x447
    STRING_ID_ENTRY(global, multiple_kill_7), // 0x448
    STRING_ID_ENTRY(global, multiple_kill_8), // 0x449
    STRING_ID_ENTRY(global, multiple_kill_9), // 0x44A
    STRING_ID_ENTRY(global, multiple_kill_10), // 0x44B
    STRING_ID_ENTRY(global, 5_kills_in_a_row), // 0x44C
    STRING_ID_ENTRY(global, 10_kills_in_a_row), // 0x44D
    STRING_ID_ENTRY(global, 15_kills_in_a_row), // 0x44E
    STRING_ID_ENTRY(global, 20_kills_in_a_row), // 0x44F
    STRING_ID_ENTRY(global, 25_kills_in_a_row), // 0x450
    STRING_ID_ENTRY(global, 30_kills_in_a_row), // 0x451
    STRING_ID_ENTRY(global, sniper_kill_5), // 0x452
    STRING_ID_ENTRY(global, sniper_kill_10), // 0x453
    STRING_ID_ENTRY(global, shotgun_kill_5), // 0x454
    STRING_ID_ENTRY(global, shotgun_kill_10), // 0x455
    STRING_ID_ENTRY(global, collision_kill_5), // 0x456
    STRING_ID_ENTRY(global, collision_kill_10), // 0x457
    STRING_ID_ENTRY(global, sword_kill_5), // 0x458
    STRING_ID_ENTRY(global, sword_kill_10), // 0x459
    STRING_ID_ENTRY(global, juggernaut_kill_5), // 0x45A
    STRING_ID_ENTRY(global, juggernaut_kill_10), // 0x45B
    STRING_ID_ENTRY(global, zombie_kill_human_5), // 0x45C
    STRING_ID_ENTRY(global, zombie_kill_human_10), // 0x45D
    STRING_ID_ENTRY(global, human_kill_zombie_5), // 0x45E
    STRING_ID_ENTRY(global, human_kill_zombie_10), // 0x45F
    STRING_ID_ENTRY(global, human_kill_zombie_15), // 0x460
    STRING_ID_ENTRY(global, koth_kill_defence_5), // 0x461
    STRING_ID_ENTRY(global, shotgun_kill_sword), // 0x462
    STRING_ID_ENTRY(global, vehicle_impact_kill), // 0x463
    STRING_ID_ENTRY(global, vehicle_hijack), // 0x464
    STRING_ID_ENTRY(global, aircraft_hijack), // 0x465
    STRING_ID_ENTRY(global, deadplayer_kill), // 0x466
    STRING_ID_ENTRY(global, player_kill_spreeplayer), // 0x467
    STRING_ID_ENTRY(global, spartanlaser_kill), // 0x468
    STRING_ID_ENTRY(global, stickygrenade_kill), // 0x469
    STRING_ID_ENTRY(global, sniper_kill), // 0x46A
    STRING_ID_ENTRY(global, bashbehind_kill), // 0x46B
    STRING_ID_ENTRY(global, bash_kill), // 0x46C
    STRING_ID_ENTRY(global, flame_kill), // 0x46D
    STRING_ID_ENTRY(global, player_kill_occupiedvehicle), // 0x46E
    STRING_ID_ENTRY(global, driver_assist_gunner), // 0x46F
    STRING_ID_ENTRY(global, assault_bomb_planted), // 0x470
    STRING_ID_ENTRY(global, assault_player_kill_carrier), // 0x471
    STRING_ID_ENTRY(global, vip_player_kill_vip), // 0x472
    STRING_ID_ENTRY(global, juggernaut_player_kill_juggernaut), // 0x473
    STRING_ID_ENTRY(global, oddball_carrier_kill_player), // 0x474
    STRING_ID_ENTRY(global, ctf_flag_captured), // 0x475
    STRING_ID_ENTRY(global, ctf_flag_player_kill_carrier), // 0x476
    STRING_ID_ENTRY(global, ctf_flag_carrier_kill_player), // 0x477
    STRING_ID_ENTRY(global, infection_survive), // 0x478
    STRING_ID_ENTRY(global, unused1), // 0x479
    STRING_ID_ENTRY(global, unused2), // 0x47A
    STRING_ID_ENTRY(global, unused3), // 0x47B
    STRING_ID_ENTRY(global, extermination_description), // 0x47C
    STRING_ID_ENTRY(global, perfection_description), // 0x47D
    STRING_ID_ENTRY(global, multiple_kill_2_description), // 0x47E
    STRING_ID_ENTRY(global, multiple_kill_3_description), // 0x47F
    STRING_ID_ENTRY(global, multiple_kill_4_description), // 0x480
    STRING_ID_ENTRY(global, multiple_kill_5_description), // 0x481
    STRING_ID_ENTRY(global, multiple_kill_6_description), // 0x482
    STRING_ID_ENTRY(global, multiple_kill_7_description), // 0x483
    STRING_ID_ENTRY(global, multiple_kill_8_description), // 0x484
    STRING_ID_ENTRY(global, multiple_kill_9_description), // 0x485
    STRING_ID_ENTRY(global, multiple_kill_10_description), // 0x486
    STRING_ID_ENTRY(global, 5_kills_in_a_row_description), // 0x487
    STRING_ID_ENTRY(global, 10_kills_in_a_row_description), // 0x488
    STRING_ID_ENTRY(global, 15_kills_in_a_row_description), // 0x489
    STRING_ID_ENTRY(global, 20_kills_in_a_row_description), // 0x48A
    STRING_ID_ENTRY(global, 25_kills_in_a_row_description), // 0x48B
    STRING_ID_ENTRY(global, 30_kills_in_a_row_description), // 0x48C
    STRING_ID_ENTRY(global, sniper_kill_5_description), // 0x48D
    STRING_ID_ENTRY(global, sniper_kill_10_description), // 0x48E
    STRING_ID_ENTRY(global, shotgun_kill_5_description), // 0x48F
    STRING_ID_ENTRY(global, shotgun_kill_10_description), // 0x490
    STRING_ID_ENTRY(global, collision_kill_5_description), // 0x491
    STRING_ID_ENTRY(global, collision_kill_10_description), // 0x492
    STRING_ID_ENTRY(global, sword_kill_5_description), // 0x493
    STRING_ID_ENTRY(global, sword_kill_10_description), // 0x494
    STRING_ID_ENTRY(global, juggernaut_kill_5_description), // 0x495
    STRING_ID_ENTRY(global, juggernaut_kill_10_description), // 0x496
    STRING_ID_ENTRY(global, zombie_kill_human_5_description), // 0x497
    STRING_ID_ENTRY(global, zombie_kill_human_10_description), // 0x498
    STRING_ID_ENTRY(global, human_kill_zombie_5_description), // 0x499
    STRING_ID_ENTRY(global, human_kill_zombie_10_description), // 0x49A
    STRING_ID_ENTRY(global, human_kill_zombie_15_description), // 0x49B
    STRING_ID_ENTRY(global, koth_kill_defence_5_description), // 0x49C
    STRING_ID_ENTRY(global, shotgun_kill_sword_description), // 0x49D
    STRING_ID_ENTRY(global, vehicle_impact_kill_description), // 0x49E
    STRING_ID_ENTRY(global, vehicle_hijack_description), // 0x49F
    STRING_ID_ENTRY(global, aircraft_hijack_description), // 0x4A0
    STRING_ID_ENTRY(global, deadplayer_kill_description), // 0x4A1
    STRING_ID_ENTRY(global, player_kill_spreeplayer_description), // 0x4A2
    STRING_ID_ENTRY(global, spartanlaser_kill_description), // 0x4A3
    STRING_ID_ENTRY(global, stickygrenade_kill_description), // 0x4A4
    STRING_ID_ENTRY(global, sniper_kill_description), // 0x4A5
    STRING_ID_ENTRY(global, bashbehind_kill_description), // 0x4A6
    STRING_ID_ENTRY(global, bash_kill_description), // 0x4A7
    STRING_ID_ENTRY(global, flame_kill_description), // 0x4A8
    STRING_ID_ENTRY(global, player_kill_occupiedvehicle_description), // 0x4A9
    STRING_ID_ENTRY(global, driver_assist_gunner_description), // 0x4AA
    STRING_ID_ENTRY(global, assault_bomb_planted_description), // 0x4AB
    STRING_ID_ENTRY(global, assault_player_kill_carrier_description), // 0x4AC
    STRING_ID_ENTRY(global, vip_player_kill_vip_description), // 0x4AD
    STRING_ID_ENTRY(global, juggernaut_player_kill_juggernaut_description), // 0x4AE
    STRING_ID_ENTRY(global, oddball_carrier_kill_player_description), // 0x4AF
    STRING_ID_ENTRY(global, ctf_flag_captured_description), // 0x4B0
    STRING_ID_ENTRY(global, ctf_flag_player_kill_carrier_description), // 0x4B1
    STRING_ID_ENTRY(global, ctf_flag_carrier_kill_player_description), // 0x4B2
    STRING_ID_ENTRY(global, infection_survive_description), // 0x4B3
    STRING_ID_ENTRY(global, unused1_description), // 0x4B4
    STRING_ID_ENTRY(global, unused2_description), // 0x4B5
    STRING_ID_ENTRY(global, unused3_description), // 0x4B6
    STRING_ID_ENTRY(global, pendulum), // 0x4B7
    STRING_ID_COUNT(global),
};
static_assert(k_string_id_namespace_global_count == 0x4B8);

/* ---------- definitions */

/* ---------- prototypes */

/* ---------- globals */

/* ---------- public code */

/* ---------- private code */

#endif // __STRING_ID_GLOBALS_H__