#ifndef __GUI_STRING_IDS_H__
#define __GUI_STRING_IDS_H__
#pragma once

/* ---------- headers */

#include "tag_files/string_ids.h"

/* ---------- constants */

enum e_string_id_gui
{
	STRING_ID_FIRST(gui),
	STRING_ID_ENTRY(gui, primary_label), // 0x10000
	STRING_ID_ENTRY(gui, secondary_label), // 0x10001
	STRING_ID_ENTRY(gui, tertiary_label), // 0x10002
	STRING_ID_ENTRY(gui, quaternary_label), // 0x10003
	STRING_ID_ENTRY(gui, header), // 0x10004
	STRING_ID_ENTRY(gui, message), // 0x10005
	STRING_ID_ENTRY(gui, spinner), // 0x10006
	STRING_ID_ENTRY(gui, proxied_datasource), // 0x10007
	STRING_ID_ENTRY(gui, colors), // 0x10008
	STRING_ID_ENTRY(gui, color_index), // 0x10009
	STRING_ID_ENTRY(gui, ring_of_light), // 0x1000A
	STRING_ID_ENTRY(gui, top_most), // 0x1000B
	STRING_ID_ENTRY(gui, bottom_most), // 0x1000C
	STRING_ID_ENTRY(gui, game_engine_index), // 0x1000D
	STRING_ID_ENTRY(gui, sort_order), // 0x1000E
	STRING_ID_ENTRY(gui, item), // 0x1000F
	STRING_ID_ENTRY(gui, target), // 0x10010
	STRING_ID_ENTRY(gui, display_group), // 0x10011
	STRING_ID_ENTRY(gui, team_color), // 0x10012
	STRING_ID_ENTRY(gui, player_index), // 0x10013
	STRING_ID_ENTRY(gui, controller_index), // 0x10014
	STRING_ID_ENTRY(gui, teams), // 0x10015
	STRING_ID_ENTRY(gui, constants), // 0x10016
	STRING_ID_ENTRY(gui, list_selection_left_bracket), // 0x10017
	STRING_ID_ENTRY(gui, list_selection_right_bracket), // 0x10018
	STRING_ID_ENTRY(gui, gamercard), // 0x10019
	STRING_ID_ENTRY(gui, service_record), // 0x1001A
	STRING_ID_ENTRY(gui, cancel), // 0x1001B
	STRING_ID_ENTRY(gui, networking), // 0x1001C
	STRING_ID_ENTRY(gui, pregame_setup_manager), // 0x1001D
	STRING_ID_ENTRY(gui, fade), // 0x1001E
	STRING_ID_ENTRY(gui, fade2), // 0x1001F
	STRING_ID_ENTRY(gui, page), // 0x10020
	STRING_ID_ENTRY(gui, widget_name), // 0x10021
	STRING_ID_ENTRY(gui, player_list), // 0x10022
	STRING_ID_ENTRY(gui, teams_list), // 0x10023
	STRING_ID_ENTRY(gui, map_id), // 0x10024
	STRING_ID_ENTRY(gui, game_name), // 0x10025
	STRING_ID_ENTRY(gui, status), // 0x10026
	STRING_ID_ENTRY(gui, type), // 0x10027
	STRING_ID_ENTRY(gui, progress), // 0x10028
	STRING_ID_ENTRY(gui, progress_border), // 0x10029
	STRING_ID_ENTRY(gui, gigabytes), // 0x1002A
	STRING_ID_ENTRY(gui, megabytes), // 0x1002B
	STRING_ID_ENTRY(gui, kilobytes), // 0x1002C
	STRING_ID_ENTRY(gui, bytes), // 0x1002D
	STRING_ID_ENTRY(gui, percentage), // 0x1002E
	STRING_ID_ENTRY(gui, filename), // 0x1002F
	STRING_ID_ENTRY(gui, yes), // 0x10030
	STRING_ID_ENTRY(gui, no), // 0x10031
	STRING_ID_ENTRY(gui, ok), // 0x10032
	STRING_ID_ENTRY(gui, pending), // 0x10033
	STRING_ID_ENTRY(gui, succeeded), // 0x10034
	STRING_ID_ENTRY(gui, failed), // 0x10035
	STRING_ID_ENTRY(gui, timer), // 0x10036
	STRING_ID_ENTRY(gui, dismiss_ui), // 0x10037
	STRING_ID_ENTRY(gui, next_player), // 0x10038
	STRING_ID_ENTRY(gui, ping), // 0x10039
	STRING_ID_ENTRY(gui, pong), // 0x1003A
	STRING_ID_ENTRY(gui, button_key_unresolved_error), // 0x1003B
	STRING_ID_ENTRY(gui, button_key_empty), // 0x1003C
	STRING_ID_ENTRY(gui, button_key_a_ok), // 0x1003D
	STRING_ID_ENTRY(gui, a_select_b_done), // 0x1003E
	STRING_ID_ENTRY(gui, a_confirm_b_cancel), // 0x1003F
	STRING_ID_ENTRY(gui, button_key_squad_leader_teams_disabled), // 0x10040
	STRING_ID_ENTRY(gui, button_key_squad_leader_teams_enabled), // 0x10041
	STRING_ID_ENTRY(gui, button_key_peon_teams_disabled), // 0x10042
	STRING_ID_ENTRY(gui, button_key_peon_teams_enabled), // 0x10043
	STRING_ID_ENTRY(gui, button_key_countdown_in_progress), // 0x10044
	STRING_ID_ENTRY(gui, button_key_countdown_in_progress_cancel), // 0x10045
	STRING_ID_ENTRY(gui, button_x), // 0x10046
	STRING_ID_ENTRY(gui, button_key_a_select_b_leave), // 0x10047
	STRING_ID_ENTRY(gui, button_key_back_stats_a_select_b_leave), // 0x10048
	STRING_ID_ENTRY(gui, button_key_a_select), // 0x10049
	STRING_ID_ENTRY(gui, button_key_x_mute_a_select), // 0x1004A
	STRING_ID_ENTRY(gui, button_key_x_unmute_a_select), // 0x1004B
	STRING_ID_ENTRY(gui, main_menu_offline), // 0x1004C
	STRING_ID_ENTRY(gui, main_menu_online), // 0x1004D
	STRING_ID_ENTRY(gui, pregame_lobby_offline), // 0x1004E
	STRING_ID_ENTRY(gui, pregame_lobby_online), // 0x1004F
	STRING_ID_ENTRY(gui, pregame_lobby_offline_team_change), // 0x10050
	STRING_ID_ENTRY(gui, pregame_lobby_online_team_change), // 0x10051
	STRING_ID_ENTRY(gui, postgame_lobby_offline), // 0x10052
	STRING_ID_ENTRY(gui, postgame_lobby_online), // 0x10053
	STRING_ID_ENTRY(gui, matchmaking_search_online), // 0x10054
	STRING_ID_ENTRY(gui, matchmaking_search_online_stats), // 0x10055
	STRING_ID_ENTRY(gui, matchmaking_search_setting_up_match), // 0x10056
	STRING_ID_ENTRY(gui, alert), // 0x10057
	STRING_ID_ENTRY(gui, default_ok), // 0x10058
	STRING_ID_ENTRY(gui, default_cancel), // 0x10059
	STRING_ID_ENTRY(gui, default_button_key), // 0x1005A
	STRING_ID_ENTRY(gui, dialog_items), // 0x1005B
	STRING_ID_ENTRY(gui, game_mode), // 0x1005C
	STRING_ID_ENTRY(gui, matchmaking), // 0x1005D
	STRING_ID_ENTRY(gui, campaign), // 0x1005E
	STRING_ID_ENTRY(gui, coop), // 0x1005F
	STRING_ID_ENTRY(gui, solo), // 0x10060
	STRING_ID_ENTRY(gui, custom_game), // 0x10061
	STRING_ID_ENTRY(gui, mapeditor), // 0x10062
	STRING_ID_ENTRY(gui, theater), // 0x10063
	STRING_ID_ENTRY(gui, gamer_zone_xbox1), // 0x10064
	STRING_ID_ENTRY(gui, gamer_zone_rr), // 0x10065
	STRING_ID_ENTRY(gui, gamer_zone_pro), // 0x10066
	STRING_ID_ENTRY(gui, gamer_zone_family), // 0x10067
	STRING_ID_ENTRY(gui, gamer_zone_underground), // 0x10068
	STRING_ID_ENTRY(gui, error_ok), // 0x10069
	STRING_ID_ENTRY(gui, main_menu), // 0x1006A
	STRING_ID_ENTRY(gui, start_menu), // 0x1006B
	STRING_ID_ENTRY(gui, start_menu_game_campaign), // 0x1006C
	STRING_ID_ENTRY(gui, start_menu_game_multiplayer), // 0x1006D
	STRING_ID_ENTRY(gui, start_menu_game_editor), // 0x1006E
	STRING_ID_ENTRY(gui, start_menu_game_saved_film), // 0x1006F
	STRING_ID_ENTRY(gui, start_menu_hq), // 0x10070
	STRING_ID_ENTRY(gui, start_menu_hq_service_record), // 0x10071
	STRING_ID_ENTRY(gui, start_menu_hq_service_record_file_share), // 0x10072
	STRING_ID_ENTRY(gui, start_menu_hq_service_record_file_share_bungie), // 0x10073
	STRING_ID_ENTRY(gui, start_menu_hq_service_record_file_share_choose_category), // 0x10074
	STRING_ID_ENTRY(gui, start_menu_hq_service_record_file_share_choose_item), // 0x10075
	STRING_ID_ENTRY(gui, start_menu_hq_service_record_file_share_item_selected), // 0x10076
	STRING_ID_ENTRY(gui, start_menu_hq_screenshots), // 0x10077
	STRING_ID_ENTRY(gui, start_menu_hq_screenshots_item_selected), // 0x10078
	STRING_ID_ENTRY(gui, start_menu_hq_screenshots_item_options), // 0x10079
	STRING_ID_ENTRY(gui, start_menu_hq_transfers), // 0x1007A
	STRING_ID_ENTRY(gui, start_menu_hq_transfers_item_selected), // 0x1007B
	STRING_ID_ENTRY(gui, start_menu_settings), // 0x1007C
	STRING_ID_ENTRY(gui, start_menu_settings_controls), // 0x1007D
	STRING_ID_ENTRY(gui, start_menu_settings_controls_button), // 0x1007E
	STRING_ID_ENTRY(gui, start_menu_settings_controls_thumbstick), // 0x1007F
	STRING_ID_ENTRY(gui, start_menu_settings_appearance), // 0x10080
	STRING_ID_ENTRY(gui, start_menu_settings_appearance_model), // 0x10081
	STRING_ID_ENTRY(gui, start_menu_settings_appearance_emblem), // 0x10082
	STRING_ID_ENTRY(gui, start_menu_settings_appearance_colors), // 0x10083
	STRING_ID_ENTRY(gui, gui_alert_toast), // 0x10084
	STRING_ID_ENTRY(gui, gui_alert_ingame_full), // 0x10085
	STRING_ID_ENTRY(gui, gui_alert_ingame_split), // 0x10086
	STRING_ID_ENTRY(gui, gui_dialog_two_items), // 0x10087
	STRING_ID_ENTRY(gui, gui_dialog_four_items), // 0x10088
	STRING_ID_ENTRY(gui, campaign_options), // 0x10089
	STRING_ID_ENTRY(gui, campaign_select_difficulty), // 0x1008A
	STRING_ID_ENTRY(gui, campaign_select_level), // 0x1008B
	STRING_ID_ENTRY(gui, campaign_loading), // 0x1008C
	STRING_ID_ENTRY(gui, pregame_lobby_campaign), // 0x1008D
	STRING_ID_ENTRY(gui, pregame_lobby_matchmaking), // 0x1008E
	STRING_ID_ENTRY(gui, pregame_lobby_multiplayer), // 0x1008F
	STRING_ID_ENTRY(gui, pregame_lobby_mapeditor), // 0x10090
	STRING_ID_ENTRY(gui, pregame_lobby_theater), // 0x10091
	STRING_ID_ENTRY(gui, pregame_selection), // 0x10092
	STRING_ID_ENTRY(gui, pregame_switch_lobby), // 0x10093
	STRING_ID_ENTRY(gui, postgame_lobby), // 0x10094
	STRING_ID_ENTRY(gui, player_select), // 0x10095
	STRING_ID_ENTRY(gui, boot_betrayer), // 0x10096
	STRING_ID_ENTRY(gui, maximum_party_size), // 0x10097
	STRING_ID_ENTRY(gui, in_progress), // 0x10098
	STRING_ID_ENTRY(gui, alpha_legal), // 0x10099
	STRING_ID_ENTRY(gui, alpha_motd), // 0x1009A
	STRING_ID_ENTRY(gui, carnage_report), // 0x1009B
	STRING_ID_ENTRY(gui, carnage_report_player_details), // 0x1009C
	STRING_ID_ENTRY(gui, scoreboard), // 0x1009D
	STRING_ID_ENTRY(gui, scoreboard_half), // 0x1009E
	STRING_ID_ENTRY(gui, scoreboard_player_select), // 0x1009F
	STRING_ID_ENTRY(gui, matchmaking_searching), // 0x100A0
	STRING_ID_ENTRY(gui, matchmaking_match_found), // 0x100A1
	STRING_ID_ENTRY(gui, pregame_advanced_options_matchmaking), // 0x100A2
	STRING_ID_ENTRY(gui, saved_film_control_pad), // 0x100A3
	STRING_ID_ENTRY(gui, game_browser_search_criteria), // 0x100A4
	STRING_ID_ENTRY(gui, medals_list), // 0x100A5
	STRING_ID_ENTRY(gui, implement_image), // 0x100A6
	STRING_ID_ENTRY(gui, implement), // 0x100A7
	STRING_ID_ENTRY(gui, implement_name), // 0x100A8
	STRING_ID_ENTRY(gui, observer_camera_list_screen), // 0x100A9
	STRING_ID_ENTRY(gui, camera_list), // 0x100AA
	STRING_ID_ENTRY(gui, camera_list_datasource), // 0x100AB
	STRING_ID_ENTRY(gui, joining_title), // 0x100AC
	STRING_ID_ENTRY(gui, joining_message), // 0x100AD
	STRING_ID_ENTRY(gui, preparing_title), // 0x100AE
	STRING_ID_ENTRY(gui, preparing_message), // 0x100AF
	STRING_ID_ENTRY(gui, pregame_selection_deleting_title), // 0x100B0
	STRING_ID_ENTRY(gui, pregame_selection_deleting_message), // 0x100B1
	STRING_ID_ENTRY(gui, file_share_deleting_title), // 0x100B2
	STRING_ID_ENTRY(gui, file_share_deleting_message), // 0x100B3
	STRING_ID_ENTRY(gui, game_variant_save_progress_title), // 0x100B4
	STRING_ID_ENTRY(gui, game_variant_save_progress_message), // 0x100B5
	STRING_ID_ENTRY(gui, map_variant_save_progress_title), // 0x100B6
	STRING_ID_ENTRY(gui, map_variant_save_progress_message), // 0x100B7
	STRING_ID_ENTRY(gui, film_save_progress_title), // 0x100B8
	STRING_ID_ENTRY(gui, film_save_progress_message), // 0x100B9
	STRING_ID_ENTRY(gui, preparing_to_upload_title), // 0x100BA
	STRING_ID_ENTRY(gui, preparing_to_upload_message), // 0x100BB
	STRING_ID_ENTRY(gui, updating_metadata_title), // 0x100BC
	STRING_ID_ENTRY(gui, updating_metadata_message), // 0x100BD
	STRING_ID_ENTRY(gui, screenshot_save_progress_title), // 0x100BE
	STRING_ID_ENTRY(gui, screenshot_save_progress_message), // 0x100BF
	STRING_ID_ENTRY(gui, start_new_campaign), // 0x100C0
	STRING_ID_ENTRY(gui, resume_campaign), // 0x100C1
	STRING_ID_ENTRY(gui, start_coop), // 0x100C2
	STRING_ID_ENTRY(gui, replay_level), // 0x100C3
	STRING_ID_ENTRY(gui, solo_last_played), // 0x100C4
	STRING_ID_ENTRY(gui, coop_last_played), // 0x100C5
	STRING_ID_ENTRY(gui, solo_easy), // 0x100C6
	STRING_ID_ENTRY(gui, solo_normal), // 0x100C7
	STRING_ID_ENTRY(gui, solo_heroic), // 0x100C8
	STRING_ID_ENTRY(gui, solo_legendary), // 0x100C9
	STRING_ID_ENTRY(gui, coop_easy), // 0x100CA
	STRING_ID_ENTRY(gui, coop_normal), // 0x100CB
	STRING_ID_ENTRY(gui, coop_heroic), // 0x100CC
	STRING_ID_ENTRY(gui, coop_legendary), // 0x100CD
	STRING_ID_ENTRY(gui, top_menu), // 0x100CE
	STRING_ID_ENTRY(gui, top_menu_cap), // 0x100CF
	STRING_ID_ENTRY(gui, sidebar), // 0x100D0
	STRING_ID_ENTRY(gui, breadcrumbs), // 0x100D1
	STRING_ID_ENTRY(gui, top_menu_display_item0), // 0x100D2
	STRING_ID_ENTRY(gui, top_menu_display_item1), // 0x100D3
	STRING_ID_ENTRY(gui, top_menu_display_item2), // 0x100D4
	STRING_ID_ENTRY(gui, sidebar_items), // 0x100D5
	STRING_ID_ENTRY(gui, appearance), // 0x100D6
	STRING_ID_ENTRY(gui, resume), // 0x100D7
	STRING_ID_ENTRY(gui, service_tag_keyboard_name), // 0x100D8
	STRING_ID_ENTRY(gui, service_tag_keyboard_description), // 0x100D9
	STRING_ID_ENTRY(gui, look_inversion), // 0x100DA
	STRING_ID_ENTRY(gui, look_inversion_normal), // 0x100DB
	STRING_ID_ENTRY(gui, look_inversion_inverted), // 0x100DC
	STRING_ID_ENTRY(gui, look_centering), // 0x100DD
	STRING_ID_ENTRY(gui, look_centering_on), // 0x100DE
	STRING_ID_ENTRY(gui, look_centering_off), // 0x100DF
	STRING_ID_ENTRY(gui, crouch_lock), // 0x100E0
	STRING_ID_ENTRY(gui, crouch_lock_on), // 0x100E1
	STRING_ID_ENTRY(gui, crouch_lock_off), // 0x100E2
	STRING_ID_ENTRY(gui, joystick_layout), // 0x100E3
	STRING_ID_ENTRY(gui, joystick_layout_standard), // 0x100E4
	STRING_ID_ENTRY(gui, joystick_layout_southpaw), // 0x100E5
	STRING_ID_ENTRY(gui, joystick_layout_legacy), // 0x100E6
	STRING_ID_ENTRY(gui, joystick_layout_legacy_southpaw), // 0x100E7
	STRING_ID_ENTRY(gui, button_layout), // 0x100E8
	STRING_ID_ENTRY(gui, button_layout_standard), // 0x100E9
	STRING_ID_ENTRY(gui, button_layout_southpaw), // 0x100EA
	STRING_ID_ENTRY(gui, button_layout_boxer), // 0x100EB
	STRING_ID_ENTRY(gui, button_layout_green_thumb), // 0x100EC
	STRING_ID_ENTRY(gui, base_color), // 0x100ED
	STRING_ID_ENTRY(gui, background_color), // 0x100EE
	STRING_ID_ENTRY(gui, color_armor1), // 0x100EF
	STRING_ID_ENTRY(gui, color_armor2), // 0x100F0
	STRING_ID_ENTRY(gui, color_armor3), // 0x100F1
	STRING_ID_ENTRY(gui, color_emblem1), // 0x100F2
	STRING_ID_ENTRY(gui, color_emblem2), // 0x100F3
	STRING_ID_ENTRY(gui, color_emblem3), // 0x100F4
	STRING_ID_ENTRY(gui, group_selector), // 0x100F5
	STRING_ID_ENTRY(gui, color_swatch_focus), // 0x100F6
	STRING_ID_ENTRY(gui, instructions_set_color), // 0x100F7
	STRING_ID_ENTRY(gui, instructions_choose_color), // 0x100F8
	STRING_ID_ENTRY(gui, model), // 0x100F9
	STRING_ID_ENTRY(gui, helmet), // 0x100FA
	STRING_ID_ENTRY(gui, leftshoulder), // 0x100FB
	STRING_ID_ENTRY(gui, rightshoulder), // 0x100FC
	STRING_ID_ENTRY(gui, part_count), // 0x100FD
	STRING_ID_ENTRY(gui, news), // 0x100FE
	STRING_ID_ENTRY(gui, achievements), // 0x100FF
	STRING_ID_ENTRY(gui, statistics), // 0x10100
	STRING_ID_ENTRY(gui, shared_files), // 0x10101
	STRING_ID_ENTRY(gui, transfers), // 0x10102
	STRING_ID_ENTRY(gui, author), // 0x10103
	STRING_ID_ENTRY(gui, date), // 0x10104
	STRING_ID_ENTRY(gui, length), // 0x10105
	STRING_ID_ENTRY(gui, size), // 0x10106
	STRING_ID_ENTRY(gui, metadata_author), // 0x10107
	STRING_ID_ENTRY(gui, metadata_date), // 0x10108
	STRING_ID_ENTRY(gui, metadata_length), // 0x10109
	STRING_ID_ENTRY(gui, metadata_size), // 0x1010A
	STRING_ID_ENTRY(gui, film), // 0x1010B
	STRING_ID_ENTRY(gui, film_clip), // 0x1010C
	STRING_ID_ENTRY(gui, film_clip_description), // 0x1010D
	STRING_ID_ENTRY(gui, campaign_film), // 0x1010E
	STRING_ID_ENTRY(gui, campaign_film_description), // 0x1010F
	STRING_ID_ENTRY(gui, multiplayer_film), // 0x10110
	STRING_ID_ENTRY(gui, multiplayer_film_description), // 0x10111
	STRING_ID_ENTRY(gui, editor_film), // 0x10112
	STRING_ID_ENTRY(gui, editor_film_description), // 0x10113
	STRING_ID_ENTRY(gui, screenshot), // 0x10114
	STRING_ID_ENTRY(gui, space_free), // 0x10115
	STRING_ID_ENTRY(gui, queued), // 0x10116
	STRING_ID_ENTRY(gui, empty), // 0x10117
	STRING_ID_ENTRY(gui, download), // 0x10118
	STRING_ID_ENTRY(gui, recommend), // 0x10119
	STRING_ID_ENTRY(gui, delete), // 0x1011A
	STRING_ID_ENTRY(gui, pro_member), // 0x1011B
	STRING_ID_ENTRY(gui, slots), // 0x1011C
	STRING_ID_ENTRY(gui, recommend_file_title), // 0x1011D
	STRING_ID_ENTRY(gui, recommend_file_game_message), // 0x1011E
	STRING_ID_ENTRY(gui, recommend_file_player_message), // 0x1011F
	STRING_ID_ENTRY(gui, recommend_file_view_file), // 0x10120
	STRING_ID_ENTRY(gui, file_share_bungie), // 0x10121
	STRING_ID_ENTRY(gui, show_service_record), // 0x10122
	STRING_ID_ENTRY(gui, show_game_details), // 0x10123
	STRING_ID_ENTRY(gui, uploading), // 0x10124
	STRING_ID_ENTRY(gui, downloading), // 0x10125
	STRING_ID_ENTRY(gui, preparing_after_download), // 0x10126
	STRING_ID_ENTRY(gui, preparing_before_upload), // 0x10127
	STRING_ID_ENTRY(gui, download_pending), // 0x10128
	STRING_ID_ENTRY(gui, upload_pending), // 0x10129
	STRING_ID_ENTRY(gui, transfer_type), // 0x1012A
	STRING_ID_ENTRY(gui, cancel_transfer), // 0x1012B
	STRING_ID_ENTRY(gui, transfer_now), // 0x1012C
	STRING_ID_ENTRY(gui, screenshots_list), // 0x1012D
	STRING_ID_ENTRY(gui, lobby_list), // 0x1012E
	STRING_ID_ENTRY(gui, switch_lobby), // 0x1012F
	STRING_ID_ENTRY(gui, title_campaign), // 0x10130
	STRING_ID_ENTRY(gui, title_matchmaking), // 0x10131
	STRING_ID_ENTRY(gui, title_multiplayer), // 0x10132
	STRING_ID_ENTRY(gui, title_mapeditor), // 0x10133
	STRING_ID_ENTRY(gui, title_theater), // 0x10134
	STRING_ID_ENTRY(gui, header_campaign), // 0x10135
	STRING_ID_ENTRY(gui, header_matchmaking), // 0x10136
	STRING_ID_ENTRY(gui, header_multiplayer), // 0x10137
	STRING_ID_ENTRY(gui, header_mapeditor), // 0x10138
	STRING_ID_ENTRY(gui, header_theater), // 0x10139
	STRING_ID_ENTRY(gui, start_game), // 0x1013A
	STRING_ID_ENTRY(gui, start_campaign_new), // 0x1013B
	STRING_ID_ENTRY(gui, start_campaign_resume), // 0x1013C
	STRING_ID_ENTRY(gui, start_campaign_coop_new), // 0x1013D
	STRING_ID_ENTRY(gui, start_campaign_coop_resume), // 0x1013E
	STRING_ID_ENTRY(gui, start_matchmaking), // 0x1013F
	STRING_ID_ENTRY(gui, start_multiplayer), // 0x10140
	STRING_ID_ENTRY(gui, start_mapeditor), // 0x10141
	STRING_ID_ENTRY(gui, start_theater), // 0x10142
	STRING_ID_ENTRY(gui, lobby_status), // 0x10143
	STRING_ID_ENTRY(gui, advanced_options), // 0x10144
	STRING_ID_ENTRY(gui, postgame_stats), // 0x10145
	STRING_ID_ENTRY(gui, options_leader), // 0x10146
	STRING_ID_ENTRY(gui, options_member), // 0x10147
	STRING_ID_ENTRY(gui, players_in_game), // 0x10148
	STRING_ID_ENTRY(gui, players_in_game_singular), // 0x10149
	STRING_ID_ENTRY(gui, players_in_game_plural), // 0x1014A
	STRING_ID_ENTRY(gui, players_in_game_singular_closed), // 0x1014B
	STRING_ID_ENTRY(gui, players_in_game_plural_closed), // 0x1014C
	STRING_ID_ENTRY(gui, subitem), // 0x1014D
	STRING_ID_ENTRY(gui, subitem_header), // 0x1014E
	STRING_ID_ENTRY(gui, select_map), // 0x1014F
	STRING_ID_ENTRY(gui, select_level), // 0x10150
	STRING_ID_ENTRY(gui, select_difficulty), // 0x10151
	STRING_ID_ENTRY(gui, select_game), // 0x10152
	STRING_ID_ENTRY(gui, select_hopper), // 0x10153
	STRING_ID_ENTRY(gui, select_film), // 0x10154
	STRING_ID_ENTRY(gui, select_network_mode), // 0x10155
	STRING_ID_ENTRY(gui, subitem_map), // 0x10156
	STRING_ID_ENTRY(gui, subitem_level), // 0x10157
	STRING_ID_ENTRY(gui, subitem_difficulty), // 0x10158
	STRING_ID_ENTRY(gui, subitem_game), // 0x10159
	STRING_ID_ENTRY(gui, subitem_hopper), // 0x1015A
	STRING_ID_ENTRY(gui, subitem_film), // 0x1015B
	STRING_ID_ENTRY(gui, subitem_network_mode), // 0x1015C
	STRING_ID_ENTRY(gui, list_empty), // 0x1015D
	STRING_ID_ENTRY(gui, recent_maps), // 0x1015E
	STRING_ID_ENTRY(gui, recent_maps_description), // 0x1015F
	STRING_ID_ENTRY(gui, recent_maps_no_hdd), // 0x10160
	STRING_ID_ENTRY(gui, recent_maps_no_items), // 0x10161
	STRING_ID_ENTRY(gui, recent_games), // 0x10162
	STRING_ID_ENTRY(gui, recent_games_description), // 0x10163
	STRING_ID_ENTRY(gui, recent_games_no_hdd), // 0x10164
	STRING_ID_ENTRY(gui, recent_games_no_items), // 0x10165
	STRING_ID_ENTRY(gui, recent_films), // 0x10166
	STRING_ID_ENTRY(gui, recent_films_description), // 0x10167
	STRING_ID_ENTRY(gui, recent_films_no_hdd), // 0x10168
	STRING_ID_ENTRY(gui, recent_films_no_items), // 0x10169
	STRING_ID_ENTRY(gui, metadata_line_1), // 0x1016A
	STRING_ID_ENTRY(gui, metadata_line_1_label), // 0x1016B
	STRING_ID_ENTRY(gui, metadata_line_2), // 0x1016C
	STRING_ID_ENTRY(gui, metadata_line_2_label), // 0x1016D
	STRING_ID_ENTRY(gui, metadata_line_3), // 0x1016E
	STRING_ID_ENTRY(gui, metadata_line_3_label), // 0x1016F
	STRING_ID_ENTRY(gui, metadata_line_4), // 0x10170
	STRING_ID_ENTRY(gui, metadata_line_4_label), // 0x10171
	STRING_ID_ENTRY(gui, team_change_delay), // 0x10172
	STRING_ID_ENTRY(gui, team_change_lying_time), // 0x10173
	STRING_ID_ENTRY(gui, easy_description), // 0x10174
	STRING_ID_ENTRY(gui, normal_description), // 0x10175
	STRING_ID_ENTRY(gui, heroic_description), // 0x10176
	STRING_ID_ENTRY(gui, legendary_description), // 0x10177
	STRING_ID_ENTRY(gui, nightmap), // 0x10178
	STRING_ID_ENTRY(gui, corrupt_file), // 0x10179
	STRING_ID_ENTRY(gui, corrupt_file_description), // 0x1017A
	STRING_ID_ENTRY(gui, hopper_population), // 0x1017B
	STRING_ID_ENTRY(gui, total_population), // 0x1017C
	STRING_ID_ENTRY(gui, edit_title), // 0x1017D
	STRING_ID_ENTRY(gui, edit_description), // 0x1017E
	STRING_ID_ENTRY(gui, edit_title_message), // 0x1017F
	STRING_ID_ENTRY(gui, edit_description_message), // 0x10180
	STRING_ID_ENTRY(gui, flavor_image), // 0x10181
	STRING_ID_ENTRY(gui, image_name), // 0x10182
	STRING_ID_ENTRY(gui, image_index), // 0x10183
	STRING_ID_ENTRY(gui, gametype_image), // 0x10184
	STRING_ID_ENTRY(gui, gametype_variant_image), // 0x10185
	STRING_ID_ENTRY(gui, map_image), // 0x10186
	STRING_ID_ENTRY(gui, level_image), // 0x10187
	STRING_ID_ENTRY(gui, difficulty_image), // 0x10188
	STRING_ID_ENTRY(gui, hopper_category_image), // 0x10189
	STRING_ID_ENTRY(gui, hopper_image), // 0x1018A
	STRING_ID_ENTRY(gui, hopper_ranked_icon_image), // 0x1018B
	STRING_ID_ENTRY(gui, advertisement_mode_image), // 0x1018C
	STRING_ID_ENTRY(gui, film_category_image), // 0x1018D
	STRING_ID_ENTRY(gui, film_image), // 0x1018E
	STRING_ID_ENTRY(gui, game_browser), // 0x1018F
	STRING_ID_ENTRY(gui, open_public_slot_count), // 0x10190
	STRING_ID_ENTRY(gui, open_private_slot_count), // 0x10191
	STRING_ID_ENTRY(gui, current_public_player_count), // 0x10192
	STRING_ID_ENTRY(gui, current_private_player_count), // 0x10193
	STRING_ID_ENTRY(gui, current_player_count), // 0x10194
	STRING_ID_ENTRY(gui, maximum_player_count), // 0x10195
	STRING_ID_ENTRY(gui, connectivity_rating), // 0x10196
	STRING_ID_ENTRY(gui, system_link_games), // 0x10197
	STRING_ID_ENTRY(gui, friends_games), // 0x10198
	STRING_ID_ENTRY(gui, xbox_live_games), // 0x10199
	STRING_ID_ENTRY(gui, party_leader), // 0x1019A
	STRING_ID_ENTRY(gui, mode), // 0x1019B
	STRING_ID_ENTRY(gui, game), // 0x1019C
	STRING_ID_ENTRY(gui, players), // 0x1019D
	STRING_ID_ENTRY(gui, privacy), // 0x1019E
	STRING_ID_ENTRY(gui, hopper_name), // 0x1019F
	STRING_ID_ENTRY(gui, map_name), // 0x101A0
	STRING_ID_ENTRY(gui, player_count), // 0x101A1
	STRING_ID_ENTRY(gui, system_link), // 0x101A2
	STRING_ID_ENTRY(gui, local), // 0x101A3
	STRING_ID_ENTRY(gui, ranked_match), // 0x101A4
	STRING_ID_ENTRY(gui, party_full), // 0x101A5
	STRING_ID_ENTRY(gui, missing_map), // 0x101A6
	STRING_ID_ENTRY(gui, censored), // 0x101A7
	STRING_ID_ENTRY(gui, player_name_info), // 0x101A8
	STRING_ID_ENTRY(gui, connection_quality), // 0x101A9
	STRING_ID_ENTRY(gui, game_details), // 0x101AA
	STRING_ID_ENTRY(gui, game_details_menu), // 0x101AB
	STRING_ID_ENTRY(gui, game_details_info), // 0x101AC
	STRING_ID_ENTRY(gui, joinable_yes), // 0x101AD
	STRING_ID_ENTRY(gui, joinable_no), // 0x101AE
	STRING_ID_ENTRY(gui, options_list), // 0x101AF
	STRING_ID_ENTRY(gui, option_join), // 0x101B0
	STRING_ID_ENTRY(gui, option_invite), // 0x101B1
	STRING_ID_ENTRY(gui, option_cantinvite), // 0x101B2
	STRING_ID_ENTRY(gui, option_message), // 0x101B3
	STRING_ID_ENTRY(gui, party_leader_heading), // 0x101B4
	STRING_ID_ENTRY(gui, party_leader_info), // 0x101B5
	STRING_ID_ENTRY(gui, players_in_party_heading), // 0x101B6
	STRING_ID_ENTRY(gui, players_in_party_info), // 0x101B7
	STRING_ID_ENTRY(gui, mode_heading), // 0x101B8
	STRING_ID_ENTRY(gui, mode_info), // 0x101B9
	STRING_ID_ENTRY(gui, status_heading), // 0x101BA
	STRING_ID_ENTRY(gui, status_info), // 0x101BB
	STRING_ID_ENTRY(gui, level_heading), // 0x101BC
	STRING_ID_ENTRY(gui, level_info), // 0x101BD
	STRING_ID_ENTRY(gui, difficulty_heading), // 0x101BE
	STRING_ID_ENTRY(gui, difficulty_info), // 0x101BF
	STRING_ID_ENTRY(gui, film_heading), // 0x101C0
	STRING_ID_ENTRY(gui, film_info), // 0x101C1
	STRING_ID_ENTRY(gui, playlist_heading), // 0x101C2
	STRING_ID_ENTRY(gui, playlist_info), // 0x101C3
	STRING_ID_ENTRY(gui, time_remaining_heading), // 0x101C4
	STRING_ID_ENTRY(gui, time_remaining_info), // 0x101C5
	STRING_ID_ENTRY(gui, score_to_win_heading), // 0x101C6
	STRING_ID_ENTRY(gui, score_to_win_info), // 0x101C7
	STRING_ID_ENTRY(gui, leading_score_heading), // 0x101C8
	STRING_ID_ENTRY(gui, leading_score_info), // 0x101C9
	STRING_ID_ENTRY(gui, game_heading), // 0x101CA
	STRING_ID_ENTRY(gui, game_info), // 0x101CB
	STRING_ID_ENTRY(gui, game_variant_heading), // 0x101CC
	STRING_ID_ENTRY(gui, game_variant_info), // 0x101CD
	STRING_ID_ENTRY(gui, map_heading), // 0x101CE
	STRING_ID_ENTRY(gui, map_info), // 0x101CF
	STRING_ID_ENTRY(gui, map_variant_heading), // 0x101D0
	STRING_ID_ENTRY(gui, map_variant_info), // 0x101D1
	STRING_ID_ENTRY(gui, teams_heading), // 0x101D2
	STRING_ID_ENTRY(gui, teams_info), // 0x101D3
	STRING_ID_ENTRY(gui, status_info_idle), // 0x101D4
	STRING_ID_ENTRY(gui, status_info_game_in_progress), // 0x101D5
	STRING_ID_ENTRY(gui, status_info_in_lobby), // 0x101D6
	STRING_ID_ENTRY(gui, status_info_matchmaking), // 0x101D7
	STRING_ID_ENTRY(gui, status_info_editing_map), // 0x101D8
	STRING_ID_ENTRY(gui, status_info_watching_a_film), // 0x101D9
	STRING_ID_ENTRY(gui, teams_info_none), // 0x101DA
	STRING_ID_ENTRY(gui, game_options), // 0x101DB
	STRING_ID_ENTRY(gui, elipsis), // 0x101DC
	STRING_ID_ENTRY(gui, undefined_option), // 0x101DD
	STRING_ID_ENTRY(gui, unchanged), // 0x101DE
	STRING_ID_ENTRY(gui, save_game_settings_name), // 0x101DF
	STRING_ID_ENTRY(gui, save_game_settings_description), // 0x101E0
	STRING_ID_ENTRY(gui, network_mode), // 0x101E1
	STRING_ID_ENTRY(gui, network_mode_description), // 0x101E2
	STRING_ID_ENTRY(gui, network_mode_xbox_live_private), // 0x101E3
	STRING_ID_ENTRY(gui, network_mode_xbox_live_private_description), // 0x101E4
	STRING_ID_ENTRY(gui, network_mode_system_link), // 0x101E5
	STRING_ID_ENTRY(gui, network_mode_system_link_description), // 0x101E6
	STRING_ID_ENTRY(gui, network_mode_offline), // 0x101E7
	STRING_ID_ENTRY(gui, network_mode_offline_description), // 0x101E8
	STRING_ID_ENTRY(gui, network_mode_xbox_live_advertise_anyone), // 0x101E9
	STRING_ID_ENTRY(gui, network_mode_xbox_live_advertise_anyone_description), // 0x101EA
	STRING_ID_ENTRY(gui, network_mode_xbox_live_advertise_friends), // 0x101EB
	STRING_ID_ENTRY(gui, network_mode_xbox_live_advertise_friends_description), // 0x101EC
	STRING_ID_ENTRY(gui, network_mode_xbox_live_advertise_invite_only), // 0x101ED
	STRING_ID_ENTRY(gui, network_mode_xbox_live_advertise_invite_only_description), // 0x101EE
	STRING_ID_ENTRY(gui, network_mode_xbox_live_browse_public), // 0x101EF
	STRING_ID_ENTRY(gui, network_mode_xbox_live_browse_public_description), // 0x101F0
	STRING_ID_ENTRY(gui, network_mode_system_link_advertise), // 0x101F1
	STRING_ID_ENTRY(gui, network_mode_system_link_advertise_description), // 0x101F2
	STRING_ID_ENTRY(gui, network_mode_system_link_browse), // 0x101F3
	STRING_ID_ENTRY(gui, network_mode_system_link_browse_description), // 0x101F4
	STRING_ID_ENTRY(gui, privacy_closed), // 0x101F5
	STRING_ID_ENTRY(gui, privacy_invite_only), // 0x101F6
	STRING_ID_ENTRY(gui, privacy_open_to_friends), // 0x101F7
	STRING_ID_ENTRY(gui, privacy_open_to_public), // 0x101F8
	STRING_ID_ENTRY(gui, privacy_full), // 0x101F9
	STRING_ID_ENTRY(gui, privacy_offline), // 0x101FA
	STRING_ID_ENTRY(gui, privacy_system_link), // 0x101FB
	STRING_ID_ENTRY(gui, roster), // 0x101FC
	STRING_ID_ENTRY(gui, player_row_type), // 0x101FD
	STRING_ID_ENTRY(gui, player_rank), // 0x101FE
	STRING_ID_ENTRY(gui, player_grade), // 0x101FF
	STRING_ID_ENTRY(gui, player_grade_short), // 0x10200
	STRING_ID_ENTRY(gui, total_xp), // 0x10201
	STRING_ID_ENTRY(gui, xp_format), // 0x10202
	STRING_ID_ENTRY(gui, player_rating), // 0x10203
	STRING_ID_ENTRY(gui, player_rank_and_grade), // 0x10204
	STRING_ID_ENTRY(gui, name_hilite), // 0x10205
	STRING_ID_ENTRY(gui, player_emblem), // 0x10206
	STRING_ID_ENTRY(gui, player_emblem_hilite), // 0x10207
	STRING_ID_ENTRY(gui, base_color_hilite), // 0x10208
	STRING_ID_ENTRY(gui, team_color_hilite), // 0x10209
	STRING_ID_ENTRY(gui, skill_level), // 0x1020A
	STRING_ID_ENTRY(gui, skill_level_hilite), // 0x1020B
	STRING_ID_ENTRY(gui, experience), // 0x1020C
	STRING_ID_ENTRY(gui, experience_hilite), // 0x1020D
	STRING_ID_ENTRY(gui, add_friend), // 0x1020E
	STRING_ID_ENTRY(gui, submit_review), // 0x1020F
	STRING_ID_ENTRY(gui, stats), // 0x10210
	STRING_ID_ENTRY(gui, matches), // 0x10211
	STRING_ID_ENTRY(gui, looking_for_player), // 0x10212
	STRING_ID_ENTRY(gui, looking_for_player2), // 0x10213
	STRING_ID_ENTRY(gui, looking_for_player3), // 0x10214
	STRING_ID_ENTRY(gui, player_found), // 0x10215
	STRING_ID_ENTRY(gui, rank_tray), // 0x10216
	STRING_ID_ENTRY(gui, rank_tray_hilite), // 0x10217
	STRING_ID_ENTRY(gui, party_bar), // 0x10218
	STRING_ID_ENTRY(gui, party_bar_player), // 0x10219
	STRING_ID_ENTRY(gui, party_bar_team), // 0x1021A
	STRING_ID_ENTRY(gui, party_bar_length), // 0x1021B
	STRING_ID_ENTRY(gui, error_state), // 0x1021C
	STRING_ID_ENTRY(gui, service_tag), // 0x1021D
	STRING_ID_ENTRY(gui, service_tag_hilite), // 0x1021E
	STRING_ID_ENTRY(gui, place), // 0x1021F
	STRING_ID_ENTRY(gui, place_hilite), // 0x10220
	STRING_ID_ENTRY(gui, score), // 0x10221
	STRING_ID_ENTRY(gui, score_hilite), // 0x10222
	STRING_ID_ENTRY(gui, observer), // 0x10223
	STRING_ID_ENTRY(gui, observer_hilite), // 0x10224
	STRING_ID_ENTRY(gui, team_bar), // 0x10225
	STRING_ID_ENTRY(gui, team_bar_hilite), // 0x10226
	STRING_ID_ENTRY(gui, cancel_storage_device_selection), // 0x10227
	STRING_ID_ENTRY(gui, controller_no_storage_device_chosen), // 0x10228
	STRING_ID_ENTRY(gui, matchmaking_hopper_switch_offline), // 0x10229
	STRING_ID_ENTRY(gui, matchmaking_hopper_switch_loading), // 0x1022A
	STRING_ID_ENTRY(gui, matchmaking_hopper_switch_failed_to_load), // 0x1022B
	STRING_ID_ENTRY(gui, tips), // 0x1022C
	STRING_ID_ENTRY(gui, tip_cycle_time), // 0x1022D
	STRING_ID_ENTRY(gui, search_preference), // 0x1022E
	STRING_ID_ENTRY(gui, search_preference_value), // 0x1022F
	STRING_ID_ENTRY(gui, search_preference_value_description), // 0x10230
	STRING_ID_ENTRY(gui, search_preference_none), // 0x10231
	STRING_ID_ENTRY(gui, search_preference_none_description), // 0x10232
	STRING_ID_ENTRY(gui, search_preference_skill), // 0x10233
	STRING_ID_ENTRY(gui, search_preference_skill_description), // 0x10234
	STRING_ID_ENTRY(gui, search_preference_connection), // 0x10235
	STRING_ID_ENTRY(gui, search_preference_connection_description), // 0x10236
	STRING_ID_ENTRY(gui, search_preference_language), // 0x10237
	STRING_ID_ENTRY(gui, search_preference_language_description), // 0x10238
	STRING_ID_ENTRY(gui, roster_status_need_more), // 0x10239
	STRING_ID_ENTRY(gui, roster_status_have_enough), // 0x1023A
	STRING_ID_ENTRY(gui, title_searching_for_match), // 0x1023B
	STRING_ID_ENTRY(gui, title_players_found), // 0x1023C
	STRING_ID_ENTRY(gui, title_game_setup), // 0x1023D
	STRING_ID_ENTRY(gui, search_stage), // 0x1023E
	STRING_ID_ENTRY(gui, status_search_stage), // 0x1023F
	STRING_ID_ENTRY(gui, status_search_stage_ideal), // 0x10240
	STRING_ID_ENTRY(gui, status_search_stage_close_skill), // 0x10241
	STRING_ID_ENTRY(gui, status_search_stage_for_any), // 0x10242
	STRING_ID_ENTRY(gui, status_search_stage_desperation), // 0x10243
	STRING_ID_ENTRY(gui, status_search_stage_waiting_for_more_players), // 0x10244
	STRING_ID_ENTRY(gui, status_search_stage_setting_up_match), // 0x10245
	STRING_ID_ENTRY(gui, status_searching_target_ranked_any), // 0x10246
	STRING_ID_ENTRY(gui, status_searching_target_ranked_party), // 0x10247
	STRING_ID_ENTRY(gui, status_searching_target_ranked_mixed), // 0x10248
	STRING_ID_ENTRY(gui, status_searching_target_unranked_any), // 0x10249
	STRING_ID_ENTRY(gui, status_searching_target_unranked_party), // 0x1024A
	STRING_ID_ENTRY(gui, status_assembling_summary_ranked_any), // 0x1024B
	STRING_ID_ENTRY(gui, status_assembling_summary_ranked_party), // 0x1024C
	STRING_ID_ENTRY(gui, status_assembling_summary_ranked_mixed), // 0x1024D
	STRING_ID_ENTRY(gui, status_assembling_summary_unranked_any), // 0x1024E
	STRING_ID_ENTRY(gui, status_assembling_summary_unranked_party), // 0x1024F
	STRING_ID_ENTRY(gui, status_setting_up_match), // 0x10250
	STRING_ID_ENTRY(gui, status_configuring_loading), // 0x10251
	STRING_ID_ENTRY(gui, status_configuring_veto_countdown), // 0x10252
	STRING_ID_ENTRY(gui, status_configuring_current_veto), // 0x10253
	STRING_ID_ENTRY(gui, status_configuring_veto_succeeded), // 0x10254
	STRING_ID_ENTRY(gui, status_configuring_veto_failed), // 0x10255
	STRING_ID_ENTRY(gui, status_configuring_game_start), // 0x10256
	STRING_ID_ENTRY(gui, status_configuring_veto_disabled), // 0x10257
	STRING_ID_ENTRY(gui, status_starting), // 0x10258
	STRING_ID_ENTRY(gui, description_configuring_veto), // 0x10259
	STRING_ID_ENTRY(gui, status_line_1), // 0x1025A
	STRING_ID_ENTRY(gui, status_line_2), // 0x1025B
	STRING_ID_ENTRY(gui, veto), // 0x1025C
	STRING_ID_ENTRY(gui, veto_activated), // 0x1025D
	STRING_ID_ENTRY(gui, matchmaking_postgame_status_rematch_disabled), // 0x1025E
	STRING_ID_ENTRY(gui, matchmaking_postgame_status_prepare_to_deploy), // 0x1025F
	STRING_ID_ENTRY(gui, matchmaking_postgame_status_party_has_voted_to_join), // 0x10260
	STRING_ID_ENTRY(gui, matchmaking_postgame_status_press_x_to_join_ranked), // 0x10261
	STRING_ID_ENTRY(gui, matchmaking_postgame_status_press_x_to_join_unranked), // 0x10262
	STRING_ID_ENTRY(gui, matchmaking_postgame_status_party_leader_can_join), // 0x10263
	STRING_ID_ENTRY(gui, matchmaking_postgame_tip_ranked_team), // 0x10264
	STRING_ID_ENTRY(gui, matchmaking_postgame_tip_ranked_ffa), // 0x10265
	STRING_ID_ENTRY(gui, matchmaking_postgame_tip_unranked_team), // 0x10266
	STRING_ID_ENTRY(gui, matchmaking_postgame_tip_unranked_ffa), // 0x10267
	STRING_ID_ENTRY(gui, timer_waiting), // 0x10268
	STRING_ID_ENTRY(gui, timer_next_match), // 0x10269
	STRING_ID_ENTRY(gui, hopper_with_population), // 0x1026A
	STRING_ID_ENTRY(gui, hopper_category_ranked), // 0x1026B
	STRING_ID_ENTRY(gui, hopper_category_ranked_description), // 0x1026C
	STRING_ID_ENTRY(gui, hopper_category_social), // 0x1026D
	STRING_ID_ENTRY(gui, hopper_category_social_description), // 0x1026E
	STRING_ID_ENTRY(gui, hopper_category_beta), // 0x1026F
	STRING_ID_ENTRY(gui, hopper_category_beta_description), // 0x10270
	STRING_ID_ENTRY(gui, hopper_category_newbie), // 0x10271
	STRING_ID_ENTRY(gui, hopper_category_newbie_description), // 0x10272
	STRING_ID_ENTRY(gui, hopper_category_community), // 0x10273
	STRING_ID_ENTRY(gui, hopper_category_community_description), // 0x10274
	STRING_ID_ENTRY(gui, unknown_error), // 0x10275
	STRING_ID_ENTRY(gui, primary_objective_1), // 0x10276
	STRING_ID_ENTRY(gui, primary_objective_2), // 0x10277
	STRING_ID_ENTRY(gui, primary_objective_3), // 0x10278
	STRING_ID_ENTRY(gui, primary_objective_4), // 0x10279
	STRING_ID_ENTRY(gui, primary_objective_5), // 0x1027A
	STRING_ID_ENTRY(gui, primary_objective_6), // 0x1027B
	STRING_ID_ENTRY(gui, primary_objective_7), // 0x1027C
	STRING_ID_ENTRY(gui, primary_objective_8), // 0x1027D
	STRING_ID_ENTRY(gui, primary_objective_9), // 0x1027E
	STRING_ID_ENTRY(gui, primary_objective_10), // 0x1027F
	STRING_ID_ENTRY(gui, secondary_objective_1), // 0x10280
	STRING_ID_ENTRY(gui, secondary_objective_2), // 0x10281
	STRING_ID_ENTRY(gui, secondary_objective_3), // 0x10282
	STRING_ID_ENTRY(gui, secondary_objective_4), // 0x10283
	STRING_ID_ENTRY(gui, secondary_objective_5), // 0x10284
	STRING_ID_ENTRY(gui, secondary_objective_6), // 0x10285
	STRING_ID_ENTRY(gui, secondary_objective_7), // 0x10286
	STRING_ID_ENTRY(gui, secondary_objective_8), // 0x10287
	STRING_ID_ENTRY(gui, secondary_objective_9), // 0x10288
	STRING_ID_ENTRY(gui, secondary_objective_10), // 0x10289
	STRING_ID_ENTRY(gui, page_results), // 0x1028A
	STRING_ID_ENTRY(gui, page_carnage), // 0x1028B
	STRING_ID_ENTRY(gui, page_killbreakdown), // 0x1028C
	STRING_ID_ENTRY(gui, page_fieldstats), // 0x1028D
	STRING_ID_ENTRY(gui, page_objectives_slayer), // 0x1028E
	STRING_ID_ENTRY(gui, page_objectives_ctf), // 0x1028F
	STRING_ID_ENTRY(gui, page_objectives_assault), // 0x10290
	STRING_ID_ENTRY(gui, page_objectives_vip), // 0x10291
	STRING_ID_ENTRY(gui, page_objectives_territories), // 0x10292
	STRING_ID_ENTRY(gui, page_objectives_oddball), // 0x10293
	STRING_ID_ENTRY(gui, page_objectives_infection), // 0x10294
	STRING_ID_ENTRY(gui, page_objectives_koth), // 0x10295
	STRING_ID_ENTRY(gui, results_place), // 0x10296
	STRING_ID_ENTRY(gui, results_score), // 0x10297
	STRING_ID_ENTRY(gui, carnage_kills), // 0x10298
	STRING_ID_ENTRY(gui, carnage_assists), // 0x10299
	STRING_ID_ENTRY(gui, carnage_deaths), // 0x1029A
	STRING_ID_ENTRY(gui, carnage_kdspread), // 0x1029B
	STRING_ID_ENTRY(gui, killbreakdown_weapon), // 0x1029C
	STRING_ID_ENTRY(gui, killbreakdown_grenade), // 0x1029D
	STRING_ID_ENTRY(gui, killbreakdown_melee), // 0x1029E
	STRING_ID_ENTRY(gui, killbreakdown_other), // 0x1029F
	STRING_ID_ENTRY(gui, fieldstats_headshots), // 0x102A0
	STRING_ID_ENTRY(gui, fieldstats_bestspree), // 0x102A1
	STRING_ID_ENTRY(gui, fieldstats_averagelife), // 0x102A2
	STRING_ID_ENTRY(gui, fieldstats_medals), // 0x102A3
	STRING_ID_ENTRY(gui, objectives_1), // 0x102A4
	STRING_ID_ENTRY(gui, objectives_2), // 0x102A5
	STRING_ID_ENTRY(gui, objectives_3), // 0x102A6
	STRING_ID_ENTRY(gui, objectives_4), // 0x102A7
	STRING_ID_ENTRY(gui, page_columns), // 0x102A8
	STRING_ID_ENTRY(gui, show_for_team_game), // 0x102A9
	STRING_ID_ENTRY(gui, players_party), // 0x102AA
	STRING_ID_ENTRY(gui, players_film), // 0x102AB
	STRING_ID_ENTRY(gui, terminal_sample), // 0x102AC
	STRING_ID_ENTRY(gui, terminal_screen), // 0x102AD
	STRING_ID_ENTRY(gui, main), // 0x102AE
	STRING_ID_ENTRY(gui, error), // 0x102AF
	STRING_ID_ENTRY(gui, error_overlay), // 0x102B0
	STRING_ID_ENTRY(gui, dummy0), // 0x102B1
	STRING_ID_ENTRY(gui, dummy1), // 0x102B2
	STRING_ID_ENTRY(gui, dummy2), // 0x102B3
	STRING_ID_ENTRY(gui, dummy3), // 0x102B4
	STRING_ID_ENTRY(gui, dummy4), // 0x102B5
	STRING_ID_ENTRY(gui, error0), // 0x102B6
	STRING_ID_ENTRY(gui, error1), // 0x102B7
	STRING_ID_ENTRY(gui, error2), // 0x102B8
	STRING_ID_ENTRY(gui, error3), // 0x102B9
	STRING_ID_ENTRY(gui, error4), // 0x102BA
	STRING_ID_ENTRY(gui, error5), // 0x102BB
	STRING_ID_ENTRY(gui, story0), // 0x102BC
	STRING_ID_ENTRY(gui, story1), // 0x102BD
	STRING_ID_ENTRY(gui, story2), // 0x102BE
	STRING_ID_ENTRY(gui, story3), // 0x102BF
	STRING_ID_ENTRY(gui, story4), // 0x102C0
	STRING_ID_ENTRY(gui, story5), // 0x102C1
	STRING_ID_ENTRY(gui, story6), // 0x102C2
	STRING_ID_ENTRY(gui, story7), // 0x102C3
	STRING_ID_ENTRY(gui, story8), // 0x102C4
	STRING_ID_ENTRY(gui, story9), // 0x102C5
	STRING_ID_ENTRY(gui, story10), // 0x102C6
	STRING_ID_ENTRY(gui, story11), // 0x102C7
	STRING_ID_ENTRY(gui, story12), // 0x102C8
	STRING_ID_ENTRY(gui, story13), // 0x102C9
	STRING_ID_ENTRY(gui, story14), // 0x102CA
	STRING_ID_ENTRY(gui, save_map), // 0x102CB
	STRING_ID_ENTRY(gui, save_map_as), // 0x102CC
	STRING_ID_ENTRY(gui, reset_map), // 0x102CD
	STRING_ID_ENTRY(gui, change_gametype), // 0x102CE
	STRING_ID_ENTRY(gui, leave_editor), // 0x102CF
	STRING_ID_ENTRY(gui, end_session), // 0x102D0
	STRING_ID_ENTRY(gui, editor), // 0x102D1
	STRING_ID_ENTRY(gui, gametype), // 0x102D2
	STRING_ID_ENTRY(gui, sandbox_budget_screen), // 0x102D3
	STRING_ID_ENTRY(gui, sandbox_objects_menu), // 0x102D4
	STRING_ID_ENTRY(gui, sandbox_object_properties_panel), // 0x102D5
	STRING_ID_ENTRY(gui, create_category_list), // 0x102D6
	STRING_ID_ENTRY(gui, create_object_list), // 0x102D7
	STRING_ID_ENTRY(gui, object_properties_list), // 0x102D8
	STRING_ID_ENTRY(gui, categories_datasource), // 0x102D9
	STRING_ID_ENTRY(gui, object_properties_datasource), // 0x102DA
	STRING_ID_ENTRY(gui, objects_datasource), // 0x102DB
	STRING_ID_ENTRY(gui, category_weapons), // 0x102DC
	STRING_ID_ENTRY(gui, category_vehicles), // 0x102DD
	STRING_ID_ENTRY(gui, category_equipment), // 0x102DE
	STRING_ID_ENTRY(gui, category_scenery), // 0x102DF
	STRING_ID_ENTRY(gui, category_teleporters), // 0x102E0
	STRING_ID_ENTRY(gui, category_spawners), // 0x102E1
	STRING_ID_ENTRY(gui, category_goals), // 0x102E2
	STRING_ID_ENTRY(gui, common_spinner), // 0x102E3
	STRING_ID_ENTRY(gui, item_cost), // 0x102E4
	STRING_ID_ENTRY(gui, items_left), // 0x102E5
	STRING_ID_ENTRY(gui, budget_datasource), // 0x102E6
	STRING_ID_ENTRY(gui, budget_available), // 0x102E7
	STRING_ID_ENTRY(gui, budget_placed), // 0x102E8
	STRING_ID_ENTRY(gui, budget_maximum), // 0x102E9
	STRING_ID_ENTRY(gui, budget_minumum), // 0x102EA
	STRING_ID_ENTRY(gui, budget_total), // 0x102EB
	STRING_ID_ENTRY(gui, budget_total_price), // 0x102EC
	STRING_ID_ENTRY(gui, respawn_rate), // 0x102ED
	STRING_ID_ENTRY(gui, spare_clips), // 0x102EE
	STRING_ID_ENTRY(gui, unique_object), // 0x102EF
	STRING_ID_ENTRY(gui, minimum_count), // 0x102F0
	STRING_ID_ENTRY(gui, maximum_count), // 0x102F1
	STRING_ID_ENTRY(gui, on_map_at_start), // 0x102F2
	STRING_ID_ENTRY(gui, teleporter_channel), // 0x102F3
	STRING_ID_ENTRY(gui, team_affiliation), // 0x102F4
	STRING_ID_ENTRY(gui, shape_type), // 0x102F5
	STRING_ID_ENTRY(gui, shape_radius), // 0x102F6
	STRING_ID_ENTRY(gui, shape_top), // 0x102F7
	STRING_ID_ENTRY(gui, shape_bottom), // 0x102F8
	STRING_ID_ENTRY(gui, shape_width), // 0x102F9
	STRING_ID_ENTRY(gui, shape_depth), // 0x102FA
	STRING_ID_ENTRY(gui, spawn_order), // 0x102FB
	STRING_ID_ENTRY(gui, saved_film_control_buttons), // 0x102FC
	STRING_ID_ENTRY(gui, button_list), // 0x102FD
	STRING_ID_ENTRY(gui, skip_back), // 0x102FE
	STRING_ID_ENTRY(gui, skip_forward), // 0x102FF
	STRING_ID_ENTRY(gui, take_screenshot), // 0x10300
	STRING_ID_ENTRY(gui, record_clip), // 0x10301
	STRING_ID_ENTRY(gui, play_film), // 0x10302
	STRING_ID_ENTRY(gui, pause_film), // 0x10303
	STRING_ID_ENTRY(gui, stop_recording), // 0x10304
	STRING_ID_ENTRY(gui, eject), // 0x10305
	STRING_ID_ENTRY(gui, leave_film), // 0x10306
	STRING_ID_ENTRY(gui, disabled_for_beta), // 0x10307
	STRING_ID_ENTRY(gui, saved_film_take_screenshot), // 0x10308
	STRING_ID_ENTRY(gui, screenshot_option_list), // 0x10309
	STRING_ID_ENTRY(gui, save_as), // 0x1030A
	STRING_ID_ENTRY(gui, save_auto), // 0x1030B
	STRING_ID_ENTRY(gui, discard), // 0x1030C
	STRING_ID_ENTRY(gui, screenshot_title_keyboard_name), // 0x1030D
	STRING_ID_ENTRY(gui, screenshot_title_keyboard_description), // 0x1030E
	STRING_ID_ENTRY(gui, screenshot_description_keyboard_name), // 0x1030F
	STRING_ID_ENTRY(gui, screenshot_description_keyboard_description), // 0x10310
	STRING_ID_ENTRY(gui, language), // 0x10311
	STRING_ID_ENTRY(gui, gamerzone), // 0x10312
	STRING_ID_ENTRY(gui, game_size), // 0x10313
	STRING_ID_ENTRY(gui, game_rules), // 0x10314
	STRING_ID_ENTRY(gui, map_size), // 0x10315
	STRING_ID_ENTRY(gui, any_language), // 0x10316
	STRING_ID_ENTRY(gui, current_language), // 0x10317
	STRING_ID_ENTRY(gui, any_gamerzone), // 0x10318
	STRING_ID_ENTRY(gui, current_gamerzone), // 0x10319
	STRING_ID_ENTRY(gui, any_experience), // 0x1031A
	STRING_ID_ENTRY(gui, current_experience_or_better), // 0x1031B
	STRING_ID_ENTRY(gui, any_game_rules), // 0x1031C
	STRING_ID_ENTRY(gui, any_game_mode), // 0x1031D
	STRING_ID_ENTRY(gui, any_game_size), // 0x1031E
	STRING_ID_ENTRY(gui, small_game_size), // 0x1031F
	STRING_ID_ENTRY(gui, medium_game_size), // 0x10320
	STRING_ID_ENTRY(gui, large_game_size), // 0x10321
	STRING_ID_ENTRY(gui, any_map_size), // 0x10322
	STRING_ID_ENTRY(gui, small_map_size), // 0x10323
	STRING_ID_ENTRY(gui, medium_map_size), // 0x10324
	STRING_ID_ENTRY(gui, large_map_size), // 0x10325
	STRING_ID_ENTRY(gui, foreground_emblem), // 0x10326
	STRING_ID_ENTRY(gui, background_emblem), // 0x10327
	STRING_ID_ENTRY(gui, saved_film_display_name), // 0x10328
	STRING_ID_ENTRY(gui, killed), // 0x10329
	STRING_ID_ENTRY(gui, killed_emblem), // 0x1032A
	STRING_ID_ENTRY(gui, killed_image), // 0x1032B
	STRING_ID_ENTRY(gui, killed_count), // 0x1032C
	STRING_ID_ENTRY(gui, killed_by), // 0x1032D
	STRING_ID_ENTRY(gui, killed_by_emblem), // 0x1032E
	STRING_ID_ENTRY(gui, killed_by_image), // 0x1032F
	STRING_ID_ENTRY(gui, killed_by_count), // 0x10330
	STRING_ID_ENTRY(gui, game_summary), // 0x10331
	STRING_ID_ENTRY(gui, mvp), // 0x10332
	STRING_ID_ENTRY(gui, victor), // 0x10333
	STRING_ID_ENTRY(gui, top_medals), // 0x10334
	STRING_ID_ENTRY(gui, game_description), // 0x10335
	STRING_ID_ENTRY(gui, player_medal), // 0x10336
	STRING_ID_ENTRY(gui, friends_enumeration_in_progress_title), // 0x10337
	STRING_ID_ENTRY(gui, friends_enumeration_in_progress_message), // 0x10338
	STRING_ID_COUNT(gui),
};
static_assert(k_string_id_namespace_gui_count == 0x10339);

/* ---------- definitions */

/* ---------- prototypes */

/* ---------- globals */

/* ---------- public code */

/* ---------- private code */

#endif // __GUI_STRING_IDS_H__